import { createCustomLevelDemo, validateCustomLevel, type CustomLevelDefinition, type CustomEnemy } from '../game/customLevel';
import type { EnemyColor, EnemyVariant, TerrainKind, InteractionDevice } from '../game/forestTypes';
import type { DamageEffectKind } from '../game/damageEffects';
import { deviceTargets } from '../game/devices';

const DRAFT_KEY='ashen-oath-editor-draft-v1', MAPS_KEY='ashen-oath-editor-maps-v1';
const colors=['Киноварь ▲','Мох ✚','Лазурь □','Охра ●','Аметист ✕'];
const sigils=['▲','✚','□','●','✕'];
const hues=['#ca7970','#9fba7c','#79b0c4','#d8b66a','#b69ad2'];
const terrains:Record<TerrainKind,string>={floor:'Пол',wall:'Стена',tree:'Дерево',puddle:'Лужа',pond:'Глубокая вода',campfire:'Костёр'};
const glyphs:Record<TerrainKind,string>={floor:'',wall:'▦',tree:'♠',puddle:'≈',pond:'≋',campfire:'♨'};
const enemies:Record<string,string>={melee:'Гоблин',ranged:'Лучник',boss:'Главарь',prism:'Огонёк',chair:'Стул',stool:'Табурет',cabinet:'Шкаф-защитник',elite:'Тяжёлый страж',sentinel:'Страж-щит',rook:'Ладья',bishop:'Слон',knight:'Конь',commander:'Командир',wizard:'Колдун',jailer:'Тюремщик',beacon:'Маяк подкреплений',wardrobe:'Гардероб 2×2'};
const attackEffects:Record<DamageEffectKind,string>={fire:'Огонь · горение',poison:'Яд · длительный урон',bleeding:'Кровотечение · при обычном движении',wind:'Ветер · усиливает горение'};
const effectOptions=(selected?:DamageEffectKind|null)=>`<option value="" ${!selected?'selected':''}>Без эффекта</option>${Object.entries(attackEffects).map(([kind,label])=>`<option value="${kind}" ${selected===kind?'selected':''}>${label}</option>`).join('')}`;
const esc=(value:unknown)=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const copy=<T>(value:T):T=>structuredClone(value);
type SavedMap={name:string;definition:CustomLevelDefinition};

/** A draft is data only. Play always passes through the same schema and game engine. */
export class LevelEditor {
  private draft:CustomLevelDefinition;
  private undoStack:CustomLevelDefinition[]=[];
  private redoStack:CustomLevelDefinition[]=[];
  private brush='enemy';
  private enemyType='melee';
  private color:EnemyColor|null=0;
  private hp=0;
  private aggressive=false;
  private attackEffect:DamageEffectKind|null=null;
  private deviceCharges=2;
  private targetDevice=-1;
  private targetStart=-1;
  private message='Выбери кисть и нарисуй свой бой. Незакрашенный пол заполняется автоматически.';
  private importError='';
  private selection=-1;
  private dragBefore:CustomLevelDefinition|null=null;
  private pointer:number|null=null;
  private jsonText='';
  private pending=false;
  constructor(private mount:HTMLElement,private play:(definition:CustomLevelDefinition)=>Promise<boolean>){
    this.draft=createCustomLevelDemo();
    try{const raw=localStorage.getItem(DRAFT_KEY);if(raw){const checked=validateCustomLevel(JSON.parse(raw));if(checked.valid&&checked.definition)this.draft=checked.definition;else{this.jsonText=raw;this.message='Сохранённый черновик не прошёл проверку. Открыта заготовка; прежний JSON оставлен в поле обмена для исправления.';}}}catch{this.message='Не удалось прочитать сохранённый черновик. Открыта новая заготовка.';}
    this.mount.addEventListener('click',e=>this.click(e));
    this.mount.addEventListener('change',e=>this.change(e));
    this.mount.addEventListener('pointerdown',e=>this.pointerDown(e));
    this.mount.addEventListener('pointermove',e=>this.pointerMove(e));
    this.mount.addEventListener('pointerup',e=>this.pointerEnd(e));
    this.mount.addEventListener('pointercancel',e=>this.pointerEnd(e));
    this.mount.addEventListener('keydown',e=>{if(e.target instanceof HTMLButtonElement&&e.target.dataset.cell&&['Enter',' '].includes(e.key)){e.preventDefault();const before=copy(this.draft);this.paint(Number(e.target.dataset.cell));this.commit(before);}});
    this.render();
  }
  get definition(){return copy(this.draft);}
  show(){this.render();}
  private stored():SavedMap[]{try{const data=JSON.parse(localStorage.getItem(MAPS_KEY)??'[]');return Array.isArray(data)?data.filter(v=>v&&typeof v.name==='string'&&v.definition).slice(0,50):[];}catch{return[];}}
  private persist(){try{localStorage.setItem(DRAFT_KEY,JSON.stringify(this.draft));}catch{this.message='Черновик остаётся в памяти. Хранилище браузера недоступно — сохрани JSON.';}}
  private commit(before:CustomLevelDefinition){if(JSON.stringify(before)!==JSON.stringify(this.draft)){this.undoStack.push(before);if(this.undoStack.length>50)this.undoStack.shift();this.redoStack=[];this.persist();}this.render();}
  private setDraft(next:CustomLevelDefinition){const before=copy(this.draft);this.draft=copy(next);this.importError='';this.selection=-1;this.targetDevice=-1;this.targetStart=-1;this.commit(before);}
  private field<T extends HTMLElement=HTMLInputElement>(id:string){return this.mount.querySelector<T>(`#${id}`)!;}
  private render(){
    const d=this.draft,v=validateCustomLevel(d),saved=this.stored();
    this.mount.innerHTML=`<style>.editor-device-options[hidden]{display:none}.editor-grid .device-arrows{background:#4b442f;color:#f2d390;border-color:#d7ad69}.editor-grid .device-fire{background:#54372c;color:#ffc088;border-color:#d88956}.editor-grid .device-target{box-shadow:inset 0 0 0 2px #e8b977}.editor-grid .target-source{outline:2px solid #ffe3a0;outline-offset:-4px}.editor-grid .target-start{outline:3px solid #f5dc8d;outline-offset:-5px}.editor-grid .editor-target-mark{position:absolute;top:1px;left:3px;color:#ffdc93;font:700 13px Arial,sans-serif;text-shadow:0 1px #31251c;pointer-events:none}.editor-device-options{width:100%}</style><div class="editor-heading"><div><p class="eyebrow">МАСТЕРСКАЯ ПОЛЕЙ</p><h1>Твой уровень</h1><p>Нарисуй поле, выбери палитру и проверь его в настоящем бою.</p></div><button class="button primary" id="editor-play" data-editor="play" ${!v.valid||this.pending?'disabled':''}>▶ ИГРАТЬ</button></div>
      <div class="editor-actions"><button data-editor="undo" ${this.undoStack.length?'':'disabled'}>↶ Отменить</button><button data-editor="redo" ${this.redoStack.length?'':'disabled'}>↷ Вернуть</button><label>Заготовка <select id="editor-preset"><option value="equal">Три равных цвета</option><option value="rare">Редкая лазурь · 100 / 100 / 20</option><option value="late">Новые цвета после цели</option></select></label><button data-editor="preset">Создать</button><button data-action="title">← К уровням</button></div>
      <p id="editor-notice" class="editor-notice" role="status">${esc(this.message)}</p>
      <div class="editor-layout"><aside class="editor-tools"><fieldset><legend>Кисть</legend><label>Что нарисовать<select id="editor-brush">${[['enemy','Противник'],['hero','Кот'],['door','Выход'],['device:arrows','Рычаг стрел'],['device:fire','Жаровня'],['device:pits','Рычаг провалов'],['targets','Цели стрел'],['pit-targets','Люки провала'],['auto','Автозаполнение'],['inspect','Пипетка'],...Object.entries(terrains).map(([key,name])=>[`terrain:${key}`,name])].map(([value,label])=>`<option value="${value}" ${this.brush===value?'selected':''}>${label}</option>`).join('')}</select></label>
      <div class="editor-device-options" ${this.brush.startsWith('device:')||this.brush==='targets'||this.brush==='pit-targets'?'':'hidden'}><label>Заряды<input id="editor-device-charges" type="number" min="0" max="99" value="${this.activeDevice()?.charges??this.deviceCharges}"></label><p class="editor-small">Стрелы: выбери рычаг, затем начало и конец прямой линии. Люки: выбери рычаг провалов и отмечай любые клетки пола или лужи; повторный щелчок убирает люк. Закрытый люк виден до срабатывания. Жаровня усиливает остаток цепи.</p><button data-editor="clear-targets" ${(d.devices??[]).some(device=>device.index===this.targetDevice&&device.kind!=='fire')?'':'disabled'}>Очистить цели</button></div>
      <div class="editor-enemy-options" ${this.brush==='enemy'?'':'hidden'}><label>Вид<select id="editor-enemy-kind">${Object.entries(enemies).map(([key,name])=>`<option value="${key}" ${this.enemyType===key?'selected':''}>${name}</option>`).join('')}</select></label><label>Цвет<select id="editor-color">${colors.map((name,i)=>`<option value="${i}" ${this.color===i?'selected':''}>${name}</option>`).join('')}<option value="neutral" ${this.color===null?'selected':''}>Бесцветный</option></select></label><label>Здоровье<input id="editor-enemy-hp" type="number" min="${this.enemyType==='prism'?1:0}" max="500" value="${this.hp}"></label><label class="editor-check"><input id="editor-aggressive" type="checkbox" ${this.aggressive?'checked':''}> Готов к атаке</label><label>Эффект удара<select id="editor-enemy-attack-effect">${effectOptions(this.attackEffect)}</select></label></div><p class="editor-small">0 HP — слабый враг: гибнет от удара и не расходует бюджет цепи. Каждая цель добавляет 1 к бюджету; цель с HP тратит своё здоровье. Проведи по клеткам для рисования. «Автозаполнение» стирает выбранного врага целиком. Кот и выход ставятся щелчком.</p></fieldset><p id="editor-cell-detail" class="editor-cell-detail">${this.describe(this.selection)}</p></aside>
      <div class="editor-board-column"><div id="editor-grid" class="editor-grid" role="grid" aria-label="Поле редактора" style="--cols:${d.cols}"></div><div class="editor-map-key"><span>♜ Кот</span><span>⇥ Выход</span><span>⚑ Рычаг</span><span>▣ Провалы</span><span>♨ Жаровня</span><span>◎ Стрелы</span><span>▤ Люк</span><span>· Случайный враг</span></div><div id="editor-errors" class="editor-errors" role="alert" ${v.valid&&!this.importError?'hidden':''}>${this.importError?`<p>${esc(this.importError)}</p>`:''}${v.errors.map(error=>`<p>${esc(error)}</p>`).join('')}</div></div>
      <aside class="editor-settings"><fieldset><legend>Уровень</legend><label>Название<input id="editor-name" maxlength="80" value="${esc(d.name)}"></label><div class="editor-pair"><label>Столбцы<input id="editor-cols" type="number" min="4" max="12" value="${d.cols}"></label><label>Строки<input id="editor-rows" type="number" min="4" max="12" value="${d.rows}"></label></div><label>Зерно случайности<input id="editor-seed" type="number" min="1" max="2147483647" value="${d.seed}"></label><label>Лимит ходов · 0 без лимита<input id="editor-turn-limit" type="number" min="0" max="999" value="${d.turnLimit}"></label><label>Здоровье кота<input id="editor-player-hp" type="number" min="1" max="20" value="${d.playerHp??5}"></label><label>Эффект удара кота<select id="editor-player-attack-effect">${effectOptions(d.playerAttackEffect)}</select></label><p class="editor-small">Эффект добавляется при попадании. Огонь и яд ранят в конце хода; кровотечение — после трёх обычных шагов. Ветер усиливает уже горящую цель.</p></fieldset>
      <fieldset><legend>Цель</legend><label>Условие<select id="editor-goal">${[['kills','Победить врагов'],['rangedKills','Победить стрелков'],['bossKills','Победить главаря'],['turns','Выдержать ходы']].map(([key,name])=>`<option value="${key}" ${d.goals[0]?.key===key?'selected':''}>${name}</option>`).join('')}</select></label><label>Количество<input id="editor-goal-target" type="number" min="1" max="999" value="${d.goals[0]?.target??8}"></label><div class="editor-extra-goals">${d.goals.slice(1).map((goal,offset)=>`<div class="editor-pair"><label>Доп. условие<select data-goal-key="${offset+1}">${[['kills','Враги'],['rangedKills','Стрелки'],['bossKills','Главари'],['turns','Ходы']].map(([key,name])=>`<option value="${key}" ${goal.key===key?'selected':' '}>${name}</option>`).join('')}</select></label><label>Количество<input data-goal-target="${offset+1}" type="number" min="1" value="${goal.target}"></label><button data-editor="remove-goal" data-goal-index="${offset+1}">Убрать условие</button></div>`).join('')}</div><button data-editor="add-goal" ${d.goals.length>=4?'disabled':' '}>+ Дополнительная цель</button><label>После цели<select id="editor-completion"><option value="exit" ${d.completion==='exit'?'selected':''}>Открыть выход · дойди цепью</option><option value="direct" ${d.completion==='direct'?'selected':''}>Сразу победить</option></select></label><p class="editor-small">Выход закрыт до выполнения цели. Дополнительные цвета вступают после цели, пока кот идёт к выходу.</p></fieldset>
      <fieldset><legend>Предметы на входе</legend><div class="editor-pair">${[['frost','Холод'],['bomb','Бомба'],['healing','Лечение'],['fire','Огонь']].map(([key,name])=>`<label>${name}<input data-editor-inventory="${key}" type="number" min="0" max="99" value="${d.inventory?.[key as 'frost']??1}"></label>`).join('')}</div></fieldset></aside></div>
      <section class="editor-palette"><h2>Палитра пополнения</h2><p>Вес — относительная частота, не проценты. 100 / 100 / 20 делает третий цвет редким. Ноль исключает цвет из случайного заполнения; нарисованные вручную враги сохраняют свой цвет. Проверка доступной цепи может менять частоты нового пополнения.</p><div class="editor-palette-rows">${colors.map((name,i)=>{const extra=d.extraColors.find(entry=>entry.color===i);return`<div class="editor-palette-row" style="--swatch:${hues[i]}"><b>${name}</b><label>Вес сначала<input data-weight="${i}" type="number" min="0" max="10000" value="${d.paletteWeights[i]}"></label><label class="editor-check"><input data-extra-enable="${i}" type="checkbox" ${extra?'checked':''}> После цели</label><label>Через ходов<input data-extra-delay="${i}" type="number" min="0" max="999" value="${extra?.afterGoalTurns??2}" ${extra?'':'disabled'}></label><label>Новый вес<input data-extra-weight="${i}" type="number" min="1" max="10000" value="${extra?.weight??100}" ${extra?'':'disabled'}></label></div>`;}).join('')}</div></section>
      <section class="editor-library"><div><h2>Мои уровни</h2><p>Сохранения живут в этом браузере. JSON переносит уровень между устройствами.</p><button data-editor="save" ${v.valid?'':'disabled'}>Сохранить по названию</button><label>Сохранённые<select id="editor-saved"><option value="">Выбери уровень</option>${saved.map((entry,i)=>`<option value="${i}">${esc(entry.name)}</option>`).join('')}</select></label><button data-editor="load">Загрузить</button><button data-editor="delete">Удалить сохранение</button></div><div><h2>Обмен уровнями</h2><div class="editor-actions"><button data-editor="export" ${v.valid?'':'disabled'}>Показать JSON</button><button data-editor="download" ${v.valid?'':'disabled'}>Скачать JSON</button><label class="editor-file">Открыть файл<input id="editor-file" type="file" accept=".json,application/json"></label></div><textarea id="editor-json" rows="7" spellcheck="false" aria-label="JSON уровня" placeholder="Вставь JSON уровня">${esc(this.jsonText)}</textarea><button data-editor="import">Импортировать JSON</button><p id="editor-import-error" role="alert">${esc(this.importError)}</p></div></section>`;
    this.renderGrid();
  }
  private selectedDevice(){return(this.draft.devices??[]).find(device=>device.index===this.selection);}
  private activeDevice(){if(this.brush==='targets'||this.brush==='pit-targets')return(this.draft.devices??[]).find(device=>device.index===this.targetDevice&&device.kind===(this.brush==='targets'?'arrows':'pits'));return this.selectedDevice();}
  private describe(index:number){if(index<0)return'Выбранная клетка появится здесь.';const d=this.draft,e=d.enemies.find(e=>(e.footprint??[e.index]).includes(index)),door=d.doors.some(e=>(e.footprint??[e.index]).includes(index)),device=(d.devices??[]).find(item=>item.index===index),arrows=(d.devices??[]).filter(item=>item.kind==='arrows'&&deviceTargets(d,item).includes(index)),pits=(d.devices??[]).filter(item=>item.kind==='pits'&&item.targets.includes(index));return`${String.fromCharCode(65+index%d.cols)}${Math.floor(index/d.cols)+1}: ${index===d.heroIndex?`кот${d.playerAttackEffect?`, удар: ${attackEffects[d.playerAttackEffect]}`:''}`:door?'выход':device?`${device.kind==='arrows'?'рычаг стрел':device.kind==='pits'?'рычаг провалов':'жаровня'}, зарядов ${device.charges}${device.kind!=='fire'?`, целей ${device.targets.length}`:''}`:e?`${enemies[e.variant??e.kind]??e.kind}, ${e.hp===0?'слабый · 0 HP':`${e.hp} HP`}, ${e.color===null?'бесцветный':colors[e.color]}${e.attackEffect?`, удар: ${attackEffects[e.attackEffect]}`:''}`:terrains[d.terrain[index]]+' · авто'}${arrows.length?` · под обстрелом (${arrows.length})`:''}${pits.length?` · закрытый люк (${pits.length})`:''}`;}
  private renderGrid(){const d=this.draft;this.field('editor-grid').innerHTML=d.terrain.map((terrain,index)=>{const e=d.enemies.find(e=>(e.footprint??[e.index]).includes(index)),door=d.doors.some(e=>(e.footprint??[e.index]).includes(index)),device=(d.devices??[]).find(item=>item.index===index),targeted=(d.devices??[]).some(item=>item.kind==='arrows'&&deviceTargets(d,item).includes(index)),pitTarget=(d.devices??[]).some(item=>item.kind==='pits'&&item.targets.includes(index)),hero=index===d.heroIndex,large=!!e?.footprint?.length;return`<button class="editor-cell terrain-${terrain} ${hero?'hero':''} ${large?'large':''} ${device?`device-${device.kind}`:''} ${targeted?'device-target':''} ${pitTarget?'editor-pit-target':''} ${(this.brush==='targets'||this.brush==='pit-targets')&&this.targetDevice===index?'target-source':''} ${this.brush==='targets'&&this.targetStart===index?'target-start':''} ${this.selection===index?'selected':''}" role="gridcell" data-cell="${index}" aria-label="${esc(this.describe(index))}" title="${esc(this.describe(index))}" style="${e?.color!==null&&e?.color!==undefined?`--enemy-color:${hues[e.color]}`:''}"><span>${hero?'♜':door?'⇥':device?.kind==='arrows'?'⚑':device?.kind==='pits'?'▣':device?.kind==='fire'?'♨':e?.kind==='prism'?'✦':e?.variant==='wardrobe'?'▥':e?.variant==='sentinel'?'▣':e?.variant==='jailer'?'⛨':e?.variant==='beacon'?'✧':e?.kind==='ranged'?'⌖':e?.kind==='boss'?'♛':e?sigils[e.color??0]:pitTarget?'▤':glyphs[terrain]||'·'}</span>${device?`<small>${device.charges}⚡</small>`:e?`<small>${e.hp===0?'◇':`${e.hp}♥`}${e.aggressive?' !':''}${e.attackEffect?' ✦':''}</small>`:''}${targeted?'<b class="editor-target-mark" aria-hidden="true">◎</b>':''}${pitTarget&&(e||hero||door||device)?'<b class="editor-pit-mark" aria-hidden="true">▤</b>':''}</button>`;}).join('');this.field('editor-cell-detail').textContent=this.describe(this.selection);}
  private clearPitTarget(index:number){for(const device of this.draft.devices??[])if(device.kind==='pits')device.targets=device.targets.filter(target=>target!==index);}
  private removeAt(index:number){this.draft.enemies=this.draft.enemies.filter(e=>!(e.footprint??[e.index]).includes(index));this.draft.doors=this.draft.doors.filter(e=>!(e.footprint??[e.index]).includes(index));this.draft.devices=(this.draft.devices??[]).filter(device=>device.index!==index);if(this.targetDevice===index){this.targetDevice=-1;this.targetStart=-1;}}
  private paint(index:number){if(index<0||index>=this.draft.terrain.length)return;this.selection=index;const d=this.draft;
    if(this.brush==='targets'||this.brush==='pit-targets'){
      const kind=this.brush==='targets'?'arrows':'pits';
      const source=(d.devices??[]).find(device=>device.index===index&&device.kind===kind);
      if(source){if(kind==='pits'&&this.targetDevice===index){source.targets=source.targets.includes(index)?source.targets.filter(target=>target!==index):[...source.targets,index];this.message=`Люков выбрано: ${source.targets.length}.`;}else{this.targetDevice=index;this.targetStart=-1;this.message=kind==='arrows'?'Рычаг выбран. Коснись первой клетки линии стрел.':'Рычаг провалов выбран. Отмечай клетки люков.';}}
      else if(kind==='pits'){
        const device=(d.devices??[]).find(item=>item.index===this.targetDevice&&item.kind==='pits');
        if(!device)this.message='Сначала коснись рычага провалов.';
        else if(!['floor','puddle'].includes(d.terrain[index]))this.message='Люк можно поставить только на пол или лужу.';
        else {device.targets=device.targets.includes(index)?device.targets.filter(target=>target!==index):[...device.targets,index];this.message=`Люков выбрано: ${device.targets.length}.`;}
      }
      else {const device=(d.devices??[]).find(item=>item.index===this.targetDevice&&item.kind==='arrows');if(!device)this.message='Сначала коснись рычага стрел.';
        else if(this.targetStart<0){this.targetStart=index;this.message='Теперь коснись последней клетки линии стрел.';}
        else {const start=this.targetStart,sameRow=Math.floor(index/d.cols)===Math.floor(start/d.cols),sameCol=index%d.cols===start%d.cols;
          if(!sameRow&&!sameCol)this.message='Цели стрел должны идти по одному ряду или столбцу.';
          else {const step=index===start?0:sameRow?Math.sign(index-start):Math.sign(index-start)*d.cols;
            const targets:number[]=[];if(step===0)targets.push(index);else for(let part=start;step>0?part<=index:part>=index;part+=step)targets.push(part);
            device.targets=targets;this.targetStart=-1;this.message=`Линия стрел: ${targets.length} кл.`;
          }
        }
      }
      this.renderGrid();return;
    }
    if(this.brush==='inspect'){const e=d.enemies.find(e=>(e.footprint??[e.index]).includes(index));if(e){this.enemyType=e.variant??e.kind;this.color=e.color;this.hp=e.hp;this.aggressive=!!e.aggressive;this.attackEffect=e.attackEffect??null;this.brush='enemy';}this.render();return;}
    if(this.brush==='hero'){this.removeAt(index);d.terrain[index]='floor';d.heroIndex=index;}
    else if(this.brush.startsWith('terrain:')){const terrain=this.brush.slice(8) as TerrainKind;if(index===d.heroIndex&&!['floor','puddle'].includes(terrain)){this.message='Сначала перенеси кота на другую клетку.';return;}this.removeAt(index);d.terrain[index]=terrain;if(!['floor','puddle'].includes(terrain))this.clearPitTarget(index);}
    else if(this.brush==='auto'){this.removeAt(index);if(index!==d.heroIndex)d.terrain[index]='floor';}
    else if(index===d.heroIndex){this.message='Сначала перенеси кота: его клетка должна оставаться свободной.';return;}
    else if(this.brush==='door'){this.removeAt(index);d.terrain[index]='floor';d.doors.push({index});}
    else if(this.brush.startsWith('device:')){
      const kind=this.brush.slice(7) as InteractionDevice['kind'];
      const current=(d.devices??[]).find(device=>device.index===index);
      if(current?.kind===kind)this.deviceCharges=current.charges;
      else {this.removeAt(index);d.terrain[index]='floor';d.devices??=[];d.devices.push({index,kind,charges:this.deviceCharges,targets:[]});}
      if(kind==='arrows'||kind==='pits')this.targetDevice=index;
    }
    else if(this.brush==='enemy'){
      const footprint=this.enemyType==='wardrobe'?[index,index+1,index+d.cols,index+d.cols+1]:undefined;
      if(footprint&&(index%d.cols===d.cols-1||Math.floor(index/d.cols)===d.rows-1||footprint.includes(d.heroIndex))){this.message='Гардеробу нужны четыре клетки 2×2 без кота.';return;}
      for(const part of footprint??[index]){this.removeAt(part);d.terrain[part]='floor';}
      const kind=['melee','ranged','boss','prism'].includes(this.enemyType)?this.enemyType:['rook','bishop','knight'].includes(this.enemyType)?'ranged':['commander','wizard','jailer','beacon'].includes(this.enemyType)?'boss':'melee';
      const cell:CustomEnemy={index,kind:kind as CustomEnemy['kind'],color:kind==='boss'||kind==='prism'?null:this.color,hp:this.hp,aggressive:this.aggressive,...this.attackEffect?{attackEffect:this.attackEffect}:{},...footprint?{footprint}:{},...this.enemyType===kind?{}:{variant:this.enemyType as EnemyVariant}};d.enemies.push(cell);
    }
    this.renderGrid();
    const chargeInput=this.mount.querySelector<HTMLInputElement>('#editor-device-charges');if(chargeInput&&this.activeDevice())chargeInput.value=String(this.activeDevice()!.charges);
  }
  private pointerDown(event:PointerEvent){const button=(event.target as HTMLElement).closest<HTMLElement>('[data-cell]');if(!button||event.button!==0||this.pointer!==null)return;event.preventDefault();this.pointer=event.pointerId;this.dragBefore=copy(this.draft);this.mount.setPointerCapture(event.pointerId);this.paint(Number(button.dataset.cell));}
  private pointerMove(event:PointerEvent){if(this.pointer!==event.pointerId||['hero','door','inspect','targets','pit-targets'].includes(this.brush)||this.brush.startsWith('device:'))return;const button=document.elementFromPoint(event.clientX,event.clientY)?.closest<HTMLElement>('[data-cell]');if(button&&this.mount.contains(button)&&Number(button.dataset.cell)!==this.selection)this.paint(Number(button.dataset.cell));}
  private pointerEnd(event:PointerEvent){if(this.pointer!==event.pointerId)return;this.pointer=null;if(this.mount.hasPointerCapture(event.pointerId))this.mount.releasePointerCapture(event.pointerId);const before=this.dragBefore;this.dragBefore=null;if(before)this.commit(before);}
  private resize(cols:number,rows:number){const d=this.draft,oldCols=d.cols,oldRows=d.rows,remap=(i:number)=>i%oldCols<cols&&Math.floor(i/oldCols)<rows?Math.floor(i/oldCols)*cols+i%oldCols:-1;d.terrain=Array.from({length:cols*rows},(_,i)=>i%cols<oldCols&&Math.floor(i/cols)<oldRows?d.terrain[Math.floor(i/cols)*oldCols+i%cols]:'floor');d.enemies=d.enemies.filter(e=>(e.footprint??[e.index]).every(i=>remap(i)>=0)).map(e=>({...e,index:remap(e.index),...e.footprint?{footprint:e.footprint.map(remap)}:{}}));d.doors=d.doors.filter(e=>(e.footprint??[e.index]).every(i=>remap(i)>=0)).map(e=>({...e,index:remap(e.index),...e.footprint?{footprint:e.footprint.map(remap)}:{}}));d.devices=(d.devices??[]).filter(device=>remap(device.index)>=0).map(device=>({...device,index:remap(device.index),targets:device.targets.map(remap).filter(index=>index>=0)}));d.heroIndex=remap(d.heroIndex)>=0?remap(d.heroIndex):cols*rows-1;d.cols=cols;d.rows=rows;this.removeAt(d.heroIndex);d.terrain[d.heroIndex]='floor';this.selection=-1;this.targetDevice=-1;this.targetStart=-1;}
  private change(event:Event){const input=event.target as HTMLInputElement|HTMLSelectElement;if(input.id==='editor-json'){this.jsonText=input.value;return;}if(input.id==='editor-file'){const file=(input as HTMLInputElement).files?.[0];if(file)void file.text().then(text=>this.importJSON(text));return;}
    if(input.id==='editor-brush'){this.brush=input.value;this.targetStart=-1;const kind=this.brush==='targets'?'arrows':this.brush==='pit-targets'?'pits':null;if(kind&&this.selectedDevice()?.kind===kind)this.targetDevice=this.selection;this.render();return;}if(input.id==='editor-enemy-kind'){this.enemyType=input.value;this.hp=input.value==='jailer'?12:input.value==='beacon'?8:['boss','wizard','commander'].includes(input.value)?20:input.value==='wardrobe'||input.value==='elite'?10:input.value==='ranged'||['sentinel','rook','bishop','knight'].includes(input.value)?7:input.value==='stool'?2:input.value==='cabinet'?4:input.value==='prism'?1:0;if(['boss','prism','commander','wizard','jailer','beacon'].includes(input.value))this.color=null;else if(this.color===null)this.color=0;this.render();return;}if(input.id==='editor-color'){this.color=input.value==='neutral'?null:Number(input.value) as EnemyColor;return;}if(input.id==='editor-enemy-hp'){const parsed=Number(input.value);this.hp=Math.max(this.enemyType==='prism'?1:0,Math.min(500,Number.isFinite(parsed)?Math.floor(parsed):0));return;}if(input.id==='editor-aggressive'){this.aggressive=(input as HTMLInputElement).checked;return;}if(input.id==='editor-enemy-attack-effect'){this.attackEffect=(input.value||null) as DamageEffectKind|null;return;}
    const before=copy(this.draft),d=this.draft,num=Number(input.value);
    if(input.id==='editor-name')d.name=input.value;
    else if(input.id==='editor-cols'||input.id==='editor-rows')this.resize(input.id==='editor-cols'?Math.max(4,Math.min(12,Math.trunc(num)||4)):d.cols,input.id==='editor-rows'?Math.max(4,Math.min(12,Math.trunc(num)||4)):d.rows);
    else if(input.id==='editor-seed')d.seed=num;
    else if(input.id==='editor-turn-limit')d.turnLimit=num;
    else if(input.id==='editor-player-hp')d.playerHp=num;
    else if(input.id==='editor-player-attack-effect'){if(input.value)d.playerAttackEffect=input.value as DamageEffectKind;else delete d.playerAttackEffect;}
    else if(input.id==='editor-device-charges'){const charges=Math.max(0,Math.min(99,Math.trunc(num)||0));this.deviceCharges=charges;const device=this.activeDevice();if(device)device.charges=charges;}
    else if(input.id==='editor-goal')d.goals=[{key:input.value as CustomLevelDefinition['goals'][number]['key'],target:d.goals[0]?.target??8},...d.goals.slice(1)];
    else if(input.id==='editor-goal-target')d.goals=[{key:d.goals[0]?.key??'kills',target:num},...d.goals.slice(1)];
    else if(input.dataset.goalKey!==undefined)d.goals[Number(input.dataset.goalKey)].key=input.value as CustomLevelDefinition['goals'][number]['key'];
    else if(input.dataset.goalTarget!==undefined)d.goals[Number(input.dataset.goalTarget)].target=num;
    else if(input.id==='editor-completion')d.completion=input.value as 'exit'|'direct';
    else if(input.dataset.weight!==undefined)d.paletteWeights[Number(input.dataset.weight)]=num;
    else if(input.dataset.extraEnable!==undefined){const color=Number(input.dataset.extraEnable) as EnemyColor;d.extraColors=d.extraColors.filter(e=>e.color!==color);if((input as HTMLInputElement).checked)d.extraColors.push({color,weight:100,afterGoalTurns:2});}
    else if(input.dataset.extraDelay!==undefined||input.dataset.extraWeight!==undefined){const color=Number(input.dataset.extraDelay??input.dataset.extraWeight),extra=d.extraColors.find(e=>e.color===color);if(extra){if(input.dataset.extraDelay!==undefined)extra.afterGoalTurns=num;else extra.weight=num;}}
    else if(input.dataset.editorInventory){d.inventory??={};d.inventory[input.dataset.editorInventory as 'frost']=num;}
    else return;
    this.importError='';this.commit(before);
  }
  private importJSON(text:string){this.jsonText=text;try{const result=validateCustomLevel(JSON.parse(text));if(!result.valid||!result.definition){this.importError=`Импорт отклонён. Черновик сохранён. ${result.errors.join(' ')}`;this.render();return;}this.message='Уровень импортирован. Проверь поле перед игрой.';this.setDraft(result.definition);}catch{this.importError='Некорректный JSON. Черновик не изменён.';this.render();}}
  private async click(event:MouseEvent){const button=(event.target as HTMLElement).closest<HTMLElement>('[data-editor]');if(!button||(button as HTMLButtonElement).disabled)return;const action=button.dataset.editor;
    if(action==='clear-targets'){const device=(this.draft.devices??[]).find(item=>item.index===this.targetDevice&&item.kind!=='fire');if(device){const before=copy(this.draft);device.targets=[];this.targetStart=-1;this.message='Цели рычага очищены.';this.commit(before);}return;}
    if(action==='add-goal'||action==='remove-goal'){const before=copy(this.draft);if(action==='remove-goal')this.draft.goals.splice(Number(button.dataset.goalIndex),1);else{const next=(['kills','rangedKills','bossKills','turns'] as const).find(key=>!this.draft.goals.some(goal=>goal.key===key));if(next)this.draft.goals.push({key:next,target:1});}this.commit(before);return;}
    if(action==='undo'||action==='redo'){const from=action==='undo'?this.undoStack:this.redoStack,to=action==='undo'?this.redoStack:this.undoStack,next=from.pop();if(next){to.push(copy(this.draft));this.draft=next;if(!(this.draft.devices??[]).some(device=>device.index===this.targetDevice))this.targetDevice=-1;this.targetStart=-1;this.persist();this.render();}return;}
    if(action==='preset'){const next=createCustomLevelDemo(),preset=this.field<HTMLSelectElement>('editor-preset').value;next.name=preset==='rare'?'Редкая лазурь':preset==='late'?'Поздние гости':'Три знамени';next.paletteWeights=preset==='rare'?[100,100,20,0,0]:[100,100,100,0,0];next.extraColors=preset==='late'?[{color:3,weight:100,afterGoalTurns:2},{color:4,weight:100,afterGoalTurns:4}]:[];this.message='Новая заготовка. Предыдущий черновик доступен через «Отменить».';this.setDraft(next);return;}
    if(action==='import'){this.importJSON(this.field<HTMLTextAreaElement>('editor-json').value);return;}
    if(action==='load'||action==='delete'){const maps=this.stored(),value=this.field<HTMLSelectElement>('editor-saved').value;if(value===''){this.message='Сначала выбери сохранённый уровень.';this.render();return;}const index=Number(value),entry=maps[index];if(!entry)return;if(action==='load'){const result=validateCustomLevel(entry.definition);if(result.valid&&result.definition){this.message=`Загружен уровень «${entry.name}».`;this.setDraft(result.definition);}else{this.importError='Сохранение повреждено. Текущий черновик не изменён.';this.render();}}else{maps.splice(index,1);try{localStorage.setItem(MAPS_KEY,JSON.stringify(maps));this.message='Сохранение удалено. Открытый черновик остался.';}catch{this.message='Не удалось изменить хранилище.';}this.render();}return;}
    const validated=validateCustomLevel(this.draft);if(!validated.valid||!validated.definition){this.render();return;}
    if(action==='save'){const maps=this.stored().filter(m=>m.name!==this.draft.name);maps.push({name:this.draft.name,definition:copy(validated.definition)});try{localStorage.setItem(MAPS_KEY,JSON.stringify(maps));this.persist();this.message=`Сохранено: «${this.draft.name}».`;}catch{this.message='Хранилище недоступно. Выбери «Скачать JSON».';}this.render();}
    else if(action==='export'||action==='download'){this.jsonText=JSON.stringify(validated.definition,null,2);if(action==='download'){const url=URL.createObjectURL(new Blob([this.jsonText],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`${this.draft.name.replace(/[^\p{L}\p{N}_-]+/gu,'_')||'level'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}this.render();}
    else if(action==='play'){this.persist();this.pending=true;this.render();try{const ok=await this.play(copy(validated.definition));if(!ok)this.message='Уровень не запустился. Черновик сохранён — проверь ошибки.';}catch(error){this.message=`Бой не начат: ${error instanceof Error?error.message:String(error)} Черновик сохранён.`;}finally{this.pending=false;this.render();}}
  }
}
