import { test, expect, type Page } from '@playwright/test';
import { availableNodes, chooseEventOption, chooseFindItem, chooseGift, chooseTalisman, createForestRun, enterNode, eventView, forestRunMap, forestRunScore, forestRunView, parseForestRun, resolveBattle, restHeal, serializeForestRun, shopLeave, type ForestRunState, type ForestRunStep } from '../src/game/run/forestRun';

// Forest map screen (docs/biomes/forest-map.md). The run model is tested in src/game/forestRun.spec.ts and
// src/game/mapGenerator.spec.ts; here the real page is driven: title entry, map, node battles, rest, find, reload,
// defeat and both bosses. A new run from the title walks a map generated by its seed; saved runs on the authored graph
// (the source of the trunk and of these routes) are built with the pure model and injected through localStorage.
test.use({ viewport: { width: 1280, height: 720 } });

const RUN_KEY = 'ashen-oath-forest-run-v1';
const JOURNAL_KEY = 'ashen-oath-playtest-v1';
const state = (page: Page) => page.evaluate(() => structuredClone((window as any).__PUZZLE_GAME.state));
const savedRun = (page: Page) => page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? 'null'), RUN_KEY);
const center = (page: Page, index: number) => page.evaluate(i => (window as any).__PUZZLE_GAME.gridToScreen(i), index);
async function settled(page: Page) {
  await expect.poll(async () => (await state(page)).phase, { timeout: 15_000 }).not.toMatch(/TITLE|RESOLVE|UPDATE/);
  await expect(page.locator('#board-host canvas')).toBeVisible();
}
async function draw(page: Page, path: number[]) {
  const first = await center(page, path[0]);
  await page.mouse.move(first.x, first.y); await page.mouse.down();
  for (const index of path.slice(1)) { const point = await center(page, index); await page.mouse.move(point.x, point.y, { steps: 4 }); }
  await expect.poll(async () => (await state(page)).chain).toEqual(path);
  await page.mouse.up(); await settled(page);
}
const node = (page: Page, id: string) => page.locator(`.map-node[data-node="${id}"]`);
const noScroll = (page: Page) => page.evaluate(() => document.documentElement.scrollHeight <= innerHeight + 1);

function ok(step: ForestRunStep): ForestRunState { if (!step.ok) throw new Error(step.reason); return step.run; }
/** Finish the pending battle as a won one with the given HP. */
function won(run: ForestRunState, hp = 5): ForestRunState {
  const pending = run.pending; if (pending?.kind !== 'battle') throw new Error('no battle');
  return ok(resolveBattle(run, { nodeId: pending.nodeId, won: true, player: { hp, maxHp: 5, energy: run.resources.player.energy }, inventory: { ...run.resources.inventory } }));
}
/** Walk the given node ids: battles are won, finds take the first option, talisman and oath choices are refused, rests heal. */
function walk(ids: string[], hp = 5, seed = 4242, ladder = 0): ForestRunState {
  let run = createForestRun(seed, { ladder });
  for (const id of ids) {
    run = ok(enterNode(run, id));
    if (run.pending?.kind === 'battle') run = won(run, hp);
    if (run.pending?.kind === 'find') run = ok(chooseFindItem(run, run.pending.options[0]));
    // A hard-battle victory offers talismans, the Jailer's oaths (docs/talismans.md).
    if (run.pending?.kind === 'talisman') run = ok(chooseTalisman(run, null));
    if (run.pending?.kind === 'rest') run = ok(restHeal(run));
  }
  return run;
}
const TRUNK = ['trunk-1', 'trunk-2', 'trunk-3', 'trunk-4'];
const TO_JAILER = [...TRUNK, 'beast-wolf', 'beast-boar', 'trail-find', 'trail-banners', 'jailer'];
/** Seed a saved run once per tab: a reload keeps whatever the page saved afterwards. */
async function seedRun(page: Page, run: ForestRunState) {
  await page.addInitScript(([key, value]) => {
    if (!sessionStorage.getItem('seeded')) { localStorage.setItem(key, value); sessionStorage.setItem('seeded', '1'); }
  }, [RUN_KEY, serializeForestRun(run)]);
}
const failOnDialog = (page: Page) => page.on('dialog', dialog => { throw new Error(`window.${dialog.type()} is not allowed: ${dialog.message()}`); });

test('title starts a run, the map shows graph, statuses, hover details and resources in 1280x720', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); failOnDialog(page);
  await page.goto('/');
  await expect(page.locator('#run-start-button')).toContainText('ПОХОД ПО ЛЕСУ');
  await page.screenshot({ path: 'artifacts/forest-map-title.png' });
  await page.locator('#run-start-button').click();
  await expect(page.locator('#map-screen')).toBeVisible();
  // A new run walks a map generated by its seed: the trunk first, then the trails, the Jailer and two branches.
  const saved = await savedRun(page);
  expect(saved.map.kind).toBe('generated');
  await expect(page.locator('#map-board')).toHaveAttribute('data-map', 'generated');
  await expect(page.locator('.map-node')).toHaveCount(saved.map.nodes.length + 4);
  // Only the first trunk battle is open; everything else is closed.
  await expect(page.locator('.map-node[data-status="available"]')).toHaveCount(1);
  await expect(node(page, 'trunk-1')).toHaveAttribute('data-status', 'available');
  await expect(node(page, 'trunk-2')).toHaveAttribute('data-status', 'locked');
  // Resources: 5 HP, 0/7 energy, no tools, 0 battles.
  await expect(page.locator('#map-hp .heart.full')).toHaveCount(5);
  await expect(page.locator('#map-energy')).toContainText('0 / 7');
  await expect(page.locator('#map-tools')).toContainText('пока закрыты');
  await expect(page.locator('#map-battles')).toContainText('0');
  // Both branches are visible: beast trail and goblin barricade, den to the Troll and camp to the Chief.
  await expect(page.locator('.map-lane-tag')).toHaveText(['Звериная тропа', 'Гоблинская засека', 'Логово зверей → Тролль', 'Лагерь гоблинов → Главарь']);
  await expect(node(page, 'den-r14c0')).toContainText('Тролль');
  await expect(node(page, 'camp-r14c0')).toContainText('Главарь');
  expect(await noScroll(page)).toBe(true);
  // Every node fits the first screen, the last row included.
  const box = await page.locator('#map-board').boundingBox();
  expect(box!.y + box!.height).toBeLessThanOrEqual(720); expect(box!.x + box!.width).toBeLessThanOrEqual(1280);
  for (const button of await page.locator('.map-node').all()) {
    const at = (await button.boundingBox())!;
    expect(at.x >= box!.x - 1 && at.x + at.width <= box!.x + box!.width + 44 && at.y >= box!.y - 4 && at.y + at.height <= 720).toBe(true);
  }
  const first = saved.map.nodes.find((entry: { id: string }) => entry.id.startsWith('r5'));
  await node(page, first.id).hover();
  await expect(page.locator('#map-detail')).toContainText('Бой из пула');
  await expect(page.locator('#map-detail')).toContainText('Открывает: Холод');
  await expect(page.locator('#map-detail')).toContainText('Цветов в пополнении: не меньше 4');
  await node(page, 'den-r14c0').hover();
  await expect(page.locator('#map-detail')).toContainText('«Логово Тролля»');
  await expect(page.locator('#map-detail')).not.toContainText('в разработке');
  await expect(page.locator('#map-detail')).toContainText('Босс');
  await node(page, 'r9c1').hover();
  await expect(page.locator('#map-detail')).toContainText('После победы открывает: Круговой удар');
  await node(page, 'trunk-4').hover();
  await expect(page.locator('#map-detail')).toContainText('Рычаг стрел');
  await expect(page.locator('#map-detail')).not.toContainText('временно');
  // A closed node cannot be entered.
  await node(page, 'trunk-2').click({ force: true });
  await expect(page.locator('#map-screen')).toBeVisible(); expect((await savedRun(page)).pending).toBeNull();
  await node(page, 'trunk-1').hover();
  await page.screenshot({ path: 'artifacts/forest-map-start.png' });
  expect(errors).toEqual([]);
});

test('a node battle is played by mouse and returns to the map with the result saved', async ({ page }) => {
  test.setTimeout(60_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.locator('#run-start-button').click();
  await node(page, 'trunk-1').click(); await settled(page);
  expect(await savedRun(page)).toMatchObject({ pending: { kind: 'battle', nodeId: 'trunk-1' } });
  // No retry counter any more: a defeat ends the run (04.10.2026).
  expect((await savedRun(page)).pending.defeats).toBeUndefined();
  // The pause of the run's battle offers no retry from the entry snapshot.
  await page.locator('[data-action="pause"]').click();
  await expect(page.locator('#modal [data-action="retry"]')).toHaveCount(0);
  await expect(page.locator('#modal [data-action="run-map"]')).toBeVisible();
  await page.locator('#modal [data-action="resume"]').click();
  const entry = await state(page);
  expect(entry.runNode.nodeId).toBe('trunk-1'); expect(entry.player.hp).toBe(5);
  await expect(page.locator('#chapter-number')).toContainText('ПОХОД');
  await expect(page.locator('#chapter-number')).not.toContainText('/ 16');
  await expect(page.locator('.chapter-select')).toHaveText('← К КАРТЕ');
  await page.screenshot({ path: 'artifacts/forest-map-battle.png' });
  // The first trunk route, as in trunk.spec.ts: E2-E3-E4 (blue), then D3-C4-B3-A2-A3-B4-C5-D5 (red, 8 defeats open the
  // door) and into the door E5: a trunk battle is won only by entering the exit.
  await draw(page, [9, 14, 19]);
  await draw(page, [13, 17, 11, 5, 10, 16, 22, 23, 24]);
  expect((await state(page)).phase).toBe('WIN');
  await expect(page.locator('#modal [data-action="run-map"]')).toContainText('К КАРТЕ');
  // The model got the result right away: a reload here would land on the map, not in a replayed battle.
  expect(await savedRun(page)).toMatchObject({ visited: ['trunk-1'], currentNodeId: 'trunk-1', pending: null });
  await page.locator('#modal [data-action="run-map"]').click();
  await expect(page.locator('#map-screen')).toBeVisible();
  await expect(node(page, 'trunk-1')).toHaveAttribute('data-status', 'current');
  await expect(node(page, 'trunk-2')).toHaveAttribute('data-status', 'available');
  await expect(page.locator('#map-battles')).toContainText('1');
  await expect(page.locator('#map-notice')).toContainText('пройден');
  expect(await noScroll(page)).toBe(true);
  // Telemetry records the attempt under the node key.
  const attempts = (await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? 'null'), JOURNAL_KEY)).attempts;
  expect(attempts.map((attempt: any) => [attempt.key, attempt.mode, attempt.nodeId, attempt.outcome])).toContainEqual(['run:trunk-wake', 'run', 'trunk-1', 'win']);
  expect(errors).toEqual([]);
});

test('HP and items carry between nodes; rest heals and reports the amount; find offers one of three', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await seedRun(page, walk(TRUNK));
  await page.goto('/');
  await expect(page.locator('#run-start-button')).toContainText('ПРОДОЛЖИТЬ ПОХОД');
  await page.locator('#run-start-button').click();
  await expect(node(page, 'beast-wolf')).toHaveAttribute('data-status', 'available');
  await expect(node(page, 'goblin-archer')).toHaveAttribute('data-status', 'available');
  await expect(node(page, 'trunk-4')).toHaveAttribute('data-status', 'current');
  // Beast wolf: lose 3 HP in the real engine, win, and the map shows 2 HP and the opened frost.
  await node(page, 'beast-wolf').click(); await settled(page);
  expect((await state(page)).runNode.allowedItems).toEqual(['frost']);
  await page.evaluate(() => (window as any).__PUZZLE_GAME.damagePlayer(3));
  await page.evaluate(() => (window as any).__PUZZLE_GAME.winLevel());
  await page.locator('#modal [data-action="run-map"]').click();
  await expect(page.locator('#map-hp .heart.full')).toHaveCount(2);
  await expect(page.locator('#map-hp .heart.empty')).toHaveCount(3);
  await expect(page.locator('#map-tools')).toContainText('Холод');
  expect((await savedRun(page)).resources.player.hp).toBe(2);
  await expect(page.locator('#map-notice')).toContainText('Открыто: Холод');
  // Rest: a choice of heal or craft; the heal gives +2 HP and the modal says how much was healed.
  await node(page, 'trail-rest').click();
  await expect(page.locator('#rest-heal')).toContainText('+2 HP');
  await expect(page.locator('#rest-craft [data-craft]')).toHaveCount(4);
  await expect(page.locator('#rest-craft [data-craft]:disabled')).toHaveCount(4);
  await page.locator('#modal [data-action="rest-heal"]').click();
  await expect(page.locator('#rest-copy')).toContainText('Вылечено: 2 HP');
  await expect(page.locator('#rest-copy')).toContainText('4 / 5');
  await page.waitForTimeout(600);
  await page.screenshot({ path: 'artifacts/forest-map-rest.png' });
  await page.locator('#modal [data-action="resume"]').click();
  await expect(page.locator('#map-hp .heart.full')).toHaveCount(4);
  await expect(node(page, 'trail-rest')).toHaveAttribute('data-status', 'current');
  expect((await savedRun(page)).visited).toContain('trail-rest');
  expect(errors).toEqual([]);
});

test('find node: choice of one of three items, saved, opened for later battles', async ({ page }) => {
  await seedRun(page, walk([...TRUNK, 'beast-wolf', 'beast-boar']));
  await page.goto('/'); await page.locator('#run-start-button').click();
  await node(page, 'trail-find').click();
  await expect(page.locator('#modal [data-find]')).toHaveCount(3);
  expect((await savedRun(page)).pending.kind).toBe('find');
  await page.waitForTimeout(600);
  await page.screenshot({ path: 'artifacts/forest-map-find.png' });
  // A reload with an open find returns to the same choice.
  await page.reload(); await page.locator('#run-start-button').click();
  await expect(page.locator('#modal [data-find]')).toHaveCount(3);
  const options: string[] = (await savedRun(page)).pending.options;
  await page.locator(`#modal [data-find="${options[1]}"]`).click();
  await expect(page.locator('#modal-layer')).toBeHidden();
  const run = await savedRun(page);
  expect(run.pending).toBeNull(); expect(run.currentNodeId).toBe('trail-find');
  expect(run.resources.inventory[options[1]]).toBeGreaterThanOrEqual(1);
  expect(run.tools.items).toContain(options[1]); expect(run.tools.abilities).toContain('jump');
  await expect(page.locator('#map-notice')).toContainText('Взято');
  await expect(page.locator('#map-tools')).toContainText('Прыжок');
  await expect(node(page, 'trail-banners')).toHaveAttribute('data-status', 'available');
});

test('reload keeps the run: map position and the start of an unfinished node battle', async ({ page }) => {
  test.setTimeout(60_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/'); await page.locator('#run-start-button').click();
  await node(page, 'trunk-1').click(); await settled(page);
  const entry = await state(page);
  await draw(page, [9, 14, 19]);
  expect((await state(page)).objective.kills).toBe(3);
  // The model does not save a battle in progress: Continue starts the node again from the entry snapshot.
  await page.reload();
  await expect(page.locator('#run-start-button')).toContainText('ПРОДОЛЖИТЬ ПОХОД');
  await page.locator('#run-start-button').click(); await settled(page);
  const restored = await state(page);
  expect(restored.runNode.nodeId).toBe('trunk-1'); expect(restored.objective.kills).toBe(0); expect(restored.turn).toBe(0);
  expect(restored.board).toEqual(entry.board);
  // A finished node comes back as a map position.
  await page.evaluate(() => (window as any).__PUZZLE_GAME.winLevel());
  await page.locator('#modal [data-action="run-map"]').click();
  await page.reload();
  await page.locator('#run-start-button').click();
  await expect(page.locator('#map-screen')).toBeVisible();
  await expect(node(page, 'trunk-1')).toHaveAttribute('data-status', 'current');
  await expect(node(page, 'trunk-2')).toHaveAttribute('data-status', 'available');
  expect(errors).toEqual([]);
});

test('a defeat ends the run: the result screen shows row, node, points and won battles; the save stays over; telemetry marks the end', async ({ page }) => {
  test.setTimeout(90_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); failOnDialog(page);
  // The cat leaves the trunk at 1 HP and enters the beast trail by mouse.
  await seedRun(page, walk(TRUNK, 1));
  await page.goto('/'); await page.locator('#run-start-button').click();
  await node(page, 'beast-wolf').click(); await settled(page);
  expect((await state(page)).player.hp).toBe(1);
  // Real play: a chain the forecast marks as deadly, drawn with the mouse; otherwise a rest until the enemies strike.
  for (let turn = 0; turn < 40 && (await state(page)).phase === 'PLAYER_INPUT'; turn++) {
    const deadly = await page.evaluate(() => { const game = (window as any).__PUZZLE_GAME; return (game.availableMoves() as number[][]).find(path => game.preview(path).playerDies) ?? null; });
    if (deadly) await draw(page, deadly);
    else { await page.locator('#wait-button').click(); await settled(page); }
  }
  expect((await state(page)).phase).toBe('LOSE');
  const score = (await state(page)).score;
  await expect(page.locator('#modal .eyebrow')).toHaveText('ПОХОД ОКОНЧЕН');
  await expect(page.locator('#modal-title')).toHaveText('Кот пал');
  await expect(page.locator('#run-result-copy')).toContainText('Вожак у брода');
  await expect(page.locator('#run-defeat-stats')).toContainText('5РЯД');
  await expect(page.locator('#run-defeat-stats')).toContainText('4БОЁВ ВЫИГРАНО');
  await expect(page.locator('#run-defeat-stats')).toContainText(`${score}ОЧКИ`);
  await expect(page.locator('#modal [data-action="run-new"]')).toHaveText('НОВЫЙ ПОХОД');
  await expect(page.locator('#modal [data-action="title"]')).toHaveText('В МЕНЮ');
  await expect(page.locator('#modal [data-action="retry"]')).toHaveCount(0);
  await expect(page.locator('#modal [data-action="run-map"]')).toHaveCount(0);
  // The score line by line (row 4 of the last completed node, four trunk battles, the battle points) and the bar of
  // openings, filled by this run's score (the first threshold is 100).
  const ended = parseForestRun(JSON.stringify(await savedRun(page)))!, total = forestRunScore(ended).total;
  await expect(page.locator('#run-score')).toContainText('Ряд 4');
  await expect(page.locator('#run-score')).toContainText('Обычные бои ×4');
  await expect(page.locator('#run-score-total')).toHaveText(String(total));
  expect(ended.tally).toMatchObject({ score: total, before: { points: 0, level: 0 }, saved: true });
  await expect(page.locator('#meta-points')).toHaveText(total >= 80 ? `${Math.min(total, 299)} / 300` : `${total} / 80`);
  await expect(page.locator('#meta-left')).toHaveText(total >= 80 ? '4' : '5');
  const lastButton = await page.locator('#modal [data-action="title"]').boundingBox();
  expect(lastButton!.y + lastButton!.height).toBeLessThanOrEqual(720);
  await page.waitForTimeout(600);
  await page.screenshot({ path: 'artifacts/forest-map-defeat.png' });
  expect(await savedRun(page)).toMatchObject({ currentNodeId: 'trunk-4', pending: null, result: { outcome: 'defeat', nodeId: 'beast-wolf' }, score });
  expect((await page.evaluate(() => JSON.parse(localStorage.getItem('ashen-oath-profile-v1') ?? 'null'))).meta.points).toBe(total >= 100 ? Math.min(total, 299) : total);
  // The saved run stays over: after a reload the title offers its result, the map has no way on.
  await page.reload();
  await expect(page.locator('#run-start-button')).toContainText('ИТОГ ПОХОДА');
  await page.locator('#run-start-button').click();
  await expect(page.locator('#modal-title')).toHaveText('Кот пал');
  await page.locator('#modal [data-action="title"]').click();
  await expect(page.locator('#title-screen')).toBeVisible();
  // Telemetry: one lost attempt that ended the run, not an abandoned node.
  const attempts = (await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? 'null'), JOURNAL_KEY)).attempts;
  const mine = attempts.filter((attempt: any) => attempt.nodeId === 'beast-wolf');
  expect(mine).toHaveLength(1);
  expect(mine[0]).toMatchObject({ mode: 'run', key: 'run:wolf-ford', id: 'wolf-ford', outcome: 'lose', runEnded: true, left: false });
  // A new run starts a fresh save. The cat reached row 5, so the profile skips the trunk in it.
  await page.locator('#run-start-button').click();
  await page.locator('#modal [data-action="run-new"]').click();
  await expect(page.locator('#map-screen')).toBeVisible();
  const fresh = await savedRun(page);
  expect(fresh.result).toBeNull(); expect(fresh.visited).toEqual([]); expect(fresh.score).toBe(0); expect(fresh.skippedTrunk).toBe(true);
  expect(errors).toEqual([]);
});

test('the trunk is played once: row 5 marks the profile, a new run starts at the fork, the playtest menu resets the mark', async ({ page }) => {
  test.setTimeout(60_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); failOnDialog(page);
  const profile = () => page.evaluate(() => JSON.parse(localStorage.getItem('ashen-oath-profile-v1') ?? 'null'));
  await seedRun(page, walk(TRUNK));
  await page.goto('/'); await page.locator('#run-start-button').click();
  expect(await profile()).toBeNull();
  // Entering the first node past the trunk marks it cleared in the profile (a separate key, outside the run save).
  await node(page, 'goblin-archer').click(); await settled(page);
  expect(await profile()).toEqual({ version: 1, trunkCleared: true, ladder: 0, giftFull: false, meta: { points: 0, level: 0 } });
  expect((await savedRun(page)).trunkCleared).toBeUndefined();
  await page.locator('[data-action="pause"]').click();
  await page.locator('#modal [data-action="title"]').click();
  // Start over: the new run begins at the trail fork; the trunk is shown as walked earlier.
  await page.locator('#run-reset-button').click();
  await page.locator('.run-confirm [data-action="run-reset-yes"]').click();
  await expect(page.locator('#map-screen')).toBeVisible();
  for (const id of TRUNK) await expect(node(page, id)).toHaveAttribute('data-status', 'skipped');
  // The start gift waits first (the mini gift: the previous run did not reach the Jailer), then row 5 opens.
  await expect(page.locator('#gift-options .gift-choice')).toHaveCount(2);
  await expect(page.locator('#gift-hint')).toHaveText('Дойди до Тюремщика — у костра будет больше.');
  await page.locator('#gift-options [data-gift="1"]').click();
  await expect(page.locator('#map-notice')).toContainText('Дар у костра');
  // The new run walks a generated map: its first choice is every node of row 5.
  const fresh = await savedRun(page), firstRow = fresh.map.nodes.filter((entry: { id: string }) => entry.id.startsWith('r5')).map((entry: { id: string }) => entry.id);
  expect(firstRow.length).toBeGreaterThanOrEqual(2);
  for (const id of firstRow) await expect(node(page, id)).toHaveAttribute('data-status', 'available');
  await expect(page.locator('.map-node[data-status="available"]')).toHaveCount(firstRow.length);
  await expect(page.locator('#map-battles')).toContainText('0');
  expect(await noScroll(page)).toBe(true);
  await page.screenshot({ path: 'artifacts/forest-map-skipped-trunk.png' });
  await node(page, 'trunk-1').hover();
  await expect(page.locator('#map-detail')).toContainText('Пройден раньше');
  // The title says where a new run starts; the playtest menu shows the mark and resets it.
  await page.locator('#map-screen [data-action="title"]').click();
  await page.locator('.playtest-link').click();
  await expect(page.locator('#playtest-profile')).toContainText('ствол пройден');
  await page.locator('[data-action="profile-reset-trunk"]').click();
  await expect(page.locator('.playtest-note')).toContainText('Отметка ствола сброшена');
  await expect(page.locator('#playtest-profile')).toContainText('ствол не пройден');
  expect(await profile()).toEqual({ version: 1, trunkCleared: false, ladder: 0, giftFull: false, meta: { points: 0, level: 0 } });
  await page.locator('[data-action="playtest-close"]').click();
  await page.locator('#run-reset-button').click();
  await page.locator('.run-confirm [data-action="run-reset-yes"]').click();
  await expect(node(page, 'trunk-1')).toHaveAttribute('data-status', 'available');
  const again = await savedRun(page);
  for (const entry of again.map.nodes.filter((item: { id: string }) => item.id.startsWith('r5'))) await expect(node(page, entry.id)).toHaveAttribute('data-status', 'locked');
  expect(errors).toEqual([]);
});

test('the start gift by mouse: a seeded run shows four buttons in 1280x720, a consumable of three opens its own choice, a reload keeps it, the item opens for the run', async ({ page }) => {
  test.setTimeout(60_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); failOnDialog(page);
  // A spread seed whose full gift starts with «выбрать 1 из 3 расходников» (searched, not fixed).
  let seed = 0;
  for (let k = 1; !seed && k < 200; k++) {
    const candidate = Math.imul(k, 2654435761) >>> 0;
    if (createForestRun(candidate, { map: 'generated', skipTrunk: true, gift: 'full' }).gift!.options[0].kind === 'pick-item') seed = candidate;
  }
  expect(seed).toBeGreaterThan(0);
  await page.addInitScript(() => { if (!sessionStorage.getItem('profiled')) { localStorage.setItem('ashen-oath-profile-v1', JSON.stringify({ version: 1, trunkCleared: true })); sessionStorage.setItem('profiled', '1'); } });
  await page.goto('/');
  await page.evaluate(value => (window as any).__PUZZLE_GAME.startForestRun(value), seed);
  await expect(page.locator('#modal .eyebrow')).toHaveText('ДАР У КОСТРА');
  await expect(page.locator('#gift-options .gift-choice')).toHaveCount(4);
  await expect(page.locator('#gift-options [data-gift="0"]')).toContainText('Выбрать 1 из 3 расходников');
  await expect(page.locator('#gift-options [data-gift="2"]')).toContainText('Талисман за цену');
  await expect(page.locator('#gift-options [data-gift="3"]')).toContainText('случайная клятва');
  await expect(page.locator('#gift-hint')).toHaveCount(0);
  expect(await noScroll(page)).toBe(true);
  const last = await page.locator('#gift-options [data-gift="3"]').boundingBox();
  expect(last!.y + last!.height).toBeLessThanOrEqual(720);
  // Headless frames start with the first input: a pointer move lets the window's fade-in finish before the shot.
  await page.mouse.move(5, 5); await page.waitForTimeout(400); await page.screenshot({ path: 'artifacts/forest-map-gift.png' });
  // The row-5 nodes wait for the gift.
  expect((await savedRun(page)).pending).toEqual({ kind: 'gift' });
  await page.locator('#gift-options [data-gift="0"]').click();
  await expect(page.locator('#gift-picks .reward-choice')).toHaveCount(3);
  const items: string[] = (await savedRun(page)).gift.options[0].items;
  // A reload keeps the open own choice of the button.
  await page.reload(); await page.locator('#run-start-button').click();
  await expect(page.locator('#gift-picks .reward-choice')).toHaveCount(3);
  await page.locator(`#gift-picks [data-gift-pick="${items[1]}"]`).click();
  await expect(page.locator('#map-notice')).toContainText('Дар у костра');
  const run = await savedRun(page);
  expect(run.gift).toMatchObject({ kind: 'full', chosen: 0, pick: items[1] });
  expect(run.tools.items).toEqual([items[1]]);
  expect(run.resources.inventory[items[1]]).toBe(1);
  await expect(page.locator('.map-node[data-status="available"]').first()).toBeVisible();
  const journal = await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? 'null'), JOURNAL_KEY);
  expect(journal.runGifts.at(-1)).toMatchObject({ kind: 'full', chosen: 0, pick: items[1], seed, seeded: true });
  expect(errors).toEqual([]);
});

test('the score and the bar of openings: a victory shows its lines and bonuses, opens one level on its own screen, the playtest resets the bar', async ({ page }) => {
  test.setTimeout(60_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); failOnDialog(page);
  const profile = () => page.evaluate(() => JSON.parse(localStorage.getItem('ashen-oath-profile-v1') ?? 'null'));
  // 75 points gathered: this victory crosses 80 (and more), but opens one level only; the surplus is cut to 299.
  await page.addInitScript(() => { if (!sessionStorage.getItem('metered')) { localStorage.setItem('ashen-oath-profile-v1', JSON.stringify({ version: 1, trunkCleared: true, meta: { points: 75, level: 0 } })); sessionStorage.setItem('metered', '1'); } });
  await seedRun(page, walk([...TO_JAILER, 'camp-battle', 'camp-rest', 'camp-elite', 'camp-breakthrough']));
  await page.goto('/'); await page.locator('#run-start-button').click();
  await node(page, 'camp-chief').click(); await settled(page);
  await page.evaluate(() => (window as any).__PUZZLE_GAME.winLevel());
  await expect(page.locator('#modal-title')).toHaveText('Главарь повержен');
  await expect(page.locator('#run-score')).toContainText('Ряд 14');
  await expect(page.locator('#run-score')).toContainText('Босс');
  await expect(page.locator('#run-score')).toContainText('Тюремщик');
  await expect(page.locator('#run-score')).toContainText('Аскет');
  const ended = parseForestRun(JSON.stringify(await savedRun(page)))!;
  await expect(page.locator('#run-score-total')).toHaveText(String(forestRunScore(ended).total));
  expect(ended.tally).toMatchObject({ before: { points: 75, level: 0 }, after: { points: 299, level: 1 }, opened: 1, saved: true });
  await expect(page.locator('#meta-points')).toHaveText('299 / 300');
  await expect(page.locator('#meta-left')).toHaveText('4');
  expect(await profile()).toMatchObject({ meta: { points: 299, level: 1 }, giftFull: true });
  const last = await page.locator('#modal [data-action="title"]').boundingBox();
  expect(last!.y + last!.height).toBeLessThanOrEqual(720);
  await page.waitForTimeout(400);
  await page.screenshot({ path: 'artifacts/forest-map-score.png' });
  // The opening: its own screen with the new talismans, then back to the result.
  await page.locator('#run-unlocks').click();
  await expect(page.locator('#modal .eyebrow')).toHaveText('ПОЛОСА ОТКРЫТИЙ · УРОВЕНЬ 1');
  await expect(page.locator('#unlock-list .unlock-item')).toHaveCount(2);
  await expect(page.locator('#unlock-list')).toContainText('Осколок жернова');
  await expect(page.locator('#unlock-list')).toContainText('Песочные часы');
  await page.waitForTimeout(400);
  await page.screenshot({ path: 'artifacts/forest-map-unlocks.png' });
  await page.locator('#modal [data-action="run-result"]').click();
  await expect(page.locator('#modal-title')).toHaveText('Главарь повержен');
  // A reload shows the same result: the bar is not filled twice.
  await page.reload(); await page.locator('#run-start-button').click();
  await expect(page.locator('#meta-points')).toHaveText('299 / 300');
  expect((await profile()).meta).toEqual({ points: 299, level: 1 });
  // A new run starts with level 1 open; the playtest window shows the bar and resets it with the gift mark.
  await page.locator('#modal [data-action="run-new"]').click();
  expect((await savedRun(page)).unlocks).toBe(1);
  await page.goto('/');
  await page.locator('.playtest-link').click();
  await expect(page.locator('#playtest-meta')).toContainText('299 / 300');
  await expect(page.locator('#playtest-meta')).toContainText('дар следующего похода: полный');
  await page.locator('[data-action="profile-reset-meta"]').click();
  await expect(page.locator('.playtest-note')).toContainText('Полоса открытий и отметка дара сброшены');
  await expect(page.locator('#playtest-meta')).toContainText('0 / 80');
  expect(await profile()).toMatchObject({ meta: { points: 0, level: 0 }, giftFull: false, trunkCleared: true });
  expect(errors).toEqual([]);
});

/**
 * A spread seed whose generated map offers, past the trunk, a first battle followed by an event whose first available
 * option completes it (not an escalation's attempt or a reward battle): the run of the page is replayed with the pure
 * model — level 0 of the bar, the full gift of an entered seed with its second button — to know the event it meets.
 */
function generatedRoute() {
  for (let k = 1; k < 400; k++) {
    const seed = Math.imul(k, 2654435761) >>> 0, run = createForestRun(seed, { map: 'generated', skipTrunk: true });
    const nodes = new Map(forestRunView(run).nodes.map(entry => [entry.node.id, entry.node]));
    for (const first of availableNodes(run)) {
      const event = first.next.map(id => nodes.get(id)!).find(next => next.type === 'event');
      if (!event) continue;
      const gifted = chooseGift(createForestRun(seed, { map: 'generated', skipTrunk: true, gift: 'full', seeded: true, unlocks: 0 }), 1);
      if (!gifted.ok || gifted.run.pending) continue;
      const entered = enterNode(gifted.run, first.id);
      if (!entered.ok || entered.run.pending?.kind !== 'battle') continue;
      const entry = entered.run.pending.entry, won = resolveBattle(entered.run, { nodeId: first.id, won: true, player: { ...entry.player }, inventory: { ...entry.inventory } });
      const atEvent = won.ok && won.run.pending === null ? enterNode(won.run, event.id) : null;
      const view = atEvent?.ok ? eventView(atEvent.run) : null, option = view?.options.find(entry => entry.available);
      if (option && !option.attempts && !option.battle) return { seed, first, event };
    }
  }
  throw new Error('no generated map with a battle and then an event');
}

test('a generated map is walked by mouse: a pooled battle shown before entering, the battle, an event, a reload keeps the map', async ({ page }) => {
  test.setTimeout(60_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); failOnDialog(page);
  const { seed, first, event } = generatedRoute();
  // The trunk was cleared in an earlier run: the run starts at the trail fork.
  await page.addInitScript(() => { if (!sessionStorage.getItem('profiled')) { localStorage.setItem('ashen-oath-profile-v1', JSON.stringify({ version: 1, trunkCleared: true })); sessionStorage.setItem('profiled', '1'); } });
  await page.goto('/');
  await page.evaluate(value => (window as any).__PUZZLE_GAME.startForestRun(value), seed);
  await expect(page.locator('#map-board')).toHaveAttribute('data-map', 'generated');
  // A run with an entered seed gets the full gift; its second button (resources, +1 maximum HP or the calm) opens no
  // tool, so the pooled battles stay as the plain run of the seed shows them.
  await expect(page.locator('#gift-options .gift-choice')).toHaveCount(4);
  await page.locator('#gift-options [data-gift="1"]').click();
  const map = (await savedRun(page)).map;
  expect(map).toEqual({ kind: 'generated', ...JSON.parse(serializeForestRun(createForestRun(seed, { map: 'generated' }))).map });
  // The available node already names its pooled battle and its feature; the event two steps away is still a pool.
  await expect(node(page, first.id)).toHaveAttribute('data-status', 'available');
  await expect(node(page, first.id)).toContainText(first.name);
  await node(page, first.id).hover();
  await expect(page.locator('#map-detail')).toContainText('Главный враг');
  await expect(page.locator('#map-detail')).toContainText(`Особенность поля: ${first.feature}`);
  await node(page, event.id).hover();
  await expect(page.locator('#map-detail')).toContainText('Событие из ещё не встреченных');
  expect(await noScroll(page)).toBe(true);
  await page.screenshot({ path: 'artifacts/forest-map-generated.png' });
  // The battle: the engine plays the pooled battle on this node's row.
  await node(page, first.id).click(); await settled(page);
  const battle = await state(page);
  expect(battle.runNode).toMatchObject({ nodeId: first.id, label: first.name, row: 5 });
  expect((await savedRun(page)).picks).toEqual([{ nodeId: first.id, battleId: (first.content as { battleId: string }).battleId }]);
  await page.evaluate(() => (window as any).__PUZZLE_GAME.winLevel());
  await page.locator('#modal [data-action="run-map"]').click();
  await expect(node(page, first.id)).toHaveAttribute('data-status', 'current');
  // The event: its node now shows which event it holds; the choice is made in the event window.
  await expect(node(page, event.id)).toHaveAttribute('data-status', 'available');
  await node(page, event.id).hover();
  await expect(page.locator('#map-detail')).toContainText('Событие «');
  await node(page, event.id).click();
  await expect(page.locator('#modal .event-choice').first()).toBeVisible();
  await page.locator('#modal .event-choice:not([disabled])').first().click();
  await expect(page.locator('#event-result')).toBeVisible();
  await page.locator('#modal [data-action="run-map"]').click();
  const after = await savedRun(page);
  expect(after).toMatchObject({ currentNodeId: event.id, pending: null, visited: [first.id, event.id] });
  expect(after.eventChoices).toHaveLength(1);
  expect(after.picks[1].nodeId).toBe(event.id);
  // A reload keeps the map, the position and the picks.
  await page.reload(); await page.locator('#run-start-button').click();
  await expect(page.locator('#map-board')).toHaveAttribute('data-map', 'generated');
  await expect(node(page, event.id)).toHaveAttribute('data-status', 'current');
  expect((await savedRun(page)).map).toEqual(map);
  expect(errors).toEqual([]);
});

test('the Troll is a real battle node; beating him wins the run; reset asks for confirmation on the page', async ({ page }) => {
  test.setTimeout(60_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); failOnDialog(page);
  await seedRun(page, walk([...TO_JAILER, 'den-battle', 'den-rest', 'den-elite', 'den-breakthrough'], 4));
  await page.goto('/'); await page.locator('#run-start-button').click();
  await expect(node(page, 'den-troll')).toHaveAttribute('data-status', 'available');
  await expect(node(page, 'den-troll')).not.toContainText('в разработке');
  await expect(node(page, 'camp-chief')).toHaveAttribute('data-status', 'locked');
  await node(page, 'den-troll').click(); await settled(page);
  const battle = await state(page);
  expect(battle.runNode.nodeId).toBe('den-troll');
  expect(battle.board.some((cell: any) => cell?.variant === 'troll')).toBe(true);
  expect(battle.player.hp).toBe(4);
  await page.evaluate(() => (window as any).__PUZZLE_GAME.winLevel());
  await expect(page.locator('#modal')).toContainText('ПОХОД ЗАВЕРШЁН');
  await expect(page.locator('#modal .outcome-symbol')).toHaveText('✦');
  await expect(page.locator('#modal')).not.toContainText('в разработке');
  await expect(page.locator('#modal [data-action="run-new"]')).toContainText('НОВЫЙ ПОХОД');
  await expect(page.locator('#modal [data-action="title"]')).toContainText('В МЕНЮ');
  expect((await savedRun(page)).result).toMatchObject({ outcome: 'victory', nodeId: 'den-troll' });
  await page.waitForTimeout(600);
  await page.screenshot({ path: 'artifacts/forest-map-troll.png' });
  await page.locator('#modal [data-action="run-map"]').click();
  await expect(node(page, 'den-troll')).toHaveAttribute('data-status', 'current');
  await expect(page.locator('.map-node[data-status="available"]')).toHaveCount(0);
  // The finished run stays saved and is shown again after a reload.
  await page.reload();
  await expect(page.locator('#run-start-button')).toContainText('ИТОГ ПОХОДА');
  // Reset: cancel keeps the save, confirm starts a new run.
  await page.locator('#run-reset-button').click();
  await expect(page.locator('.run-confirm')).toContainText('Стереть сохранённый поход?');
  await page.locator('.run-confirm [data-action="run-reset-no"]').click();
  await expect(page.locator('.run-confirm')).toHaveCount(0);
  expect((await savedRun(page)).result).not.toBeNull();
  await page.locator('#run-reset-button').click();
  await page.locator('.run-confirm [data-action="run-reset-yes"]').click();
  await expect(page.locator('#map-screen')).toBeVisible();
  const fresh = await savedRun(page);
  expect(fresh.visited).toEqual([]); expect(fresh.result).toBeNull(); expect(fresh.resources.player.hp).toBe(5);
  // Entering the Troll's node (past the trunk) marked the trunk as cleared: the new run starts at the trail fork.
  expect(fresh.skippedTrunk).toBe(true);
  await expect(node(page, 'trunk-1')).toHaveAttribute('data-status', 'skipped');
  // The new run walks a generated map and starts at its first trail row, after the start gift: the won run reached the
  // Jailer, so the gift is the full one.
  expect(fresh.map.kind).toBe('generated');
  await expect(page.locator('#gift-options .gift-choice')).toHaveCount(4);
  expect((await page.evaluate(() => JSON.parse(localStorage.getItem('ashen-oath-profile-v1') ?? 'null'))).giftFull).toBe(true);
  await page.locator('#gift-options [data-gift="1"]').click();
  await expect(node(page, fresh.map.nodes.find((entry: { id: string }) => entry.id.startsWith('r5')).id)).toHaveAttribute('data-status', 'available');
  // The same confirmation on the map.
  await page.locator('.map-actions [data-action="run-reset"]').click();
  await expect(page.locator('.map-confirm')).toContainText('Сбросить поход');
  await page.locator('.map-confirm [data-action="run-reset-no"]').click();
  await expect(page.locator('.map-confirm')).toHaveCount(0);
  expect(errors).toEqual([]);
});

test('the Chief is a real battle node; beating him ends the run with a victory', async ({ page }) => {
  test.setTimeout(60_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await seedRun(page, walk([...TO_JAILER, 'camp-battle', 'camp-rest', 'camp-elite', 'camp-breakthrough']));
  await page.goto('/'); await page.locator('#run-start-button').click();
  await node(page, 'camp-chief').click(); await settled(page);
  const battle = await state(page);
  expect(battle.runNode.nodeId).toBe('camp-chief');
  // An ordinary authored battle: the Chief stands on the field from the start, no waves.
  expect(battle.board.some((cell: any) => cell?.kind === 'boss' && !cell.variant)).toBe(true);
  await expect(page.locator('#chapter-number')).toContainText('ПОХОД');
  await page.evaluate(() => (window as any).__PUZZLE_GAME.winLevel());
  await expect(page.locator('#modal')).toContainText('Главарь повержен');
  await expect(page.locator('#modal [data-action="run-new"]')).toBeVisible();
  expect((await savedRun(page)).result).toMatchObject({ outcome: 'victory', nodeId: 'camp-chief' });
  await page.waitForTimeout(600);
  await page.screenshot({ path: 'artifacts/forest-map-victory.png' });
  await page.locator('#modal [data-action="run-map"]').click();
  await expect(node(page, 'camp-chief')).toHaveAttribute('data-status', 'current');
  await page.screenshot({ path: 'artifacts/forest-map-late.png' });
  expect(errors).toEqual([]);
});

test('«Ступени клятвы»: the title picks the step (the highest open by default, changes on request), the map and the result show it, a victory opens the next', async ({ page }) => {
  test.setTimeout(60_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); failOnDialog(page);
  const profile = () => page.evaluate(() => JSON.parse(localStorage.getItem('ashen-oath-profile-v1') ?? 'null'));
  await page.addInitScript(() => { if (!sessionStorage.getItem('laddered')) { localStorage.setItem('ashen-oath-profile-v1', JSON.stringify({ version: 1, trunkCleared: true, ladder: 3 })); sessionStorage.setItem('laddered', '1'); } });
  await page.goto('/');
  // The highest open step is chosen; the changes are listed only on request.
  await expect(page.locator('#ladder-value')).toHaveText('3');
  await expect(page.locator('#run-start-button')).toContainText('ступень 3');
  await expect(page.locator('#ladder-pick .ladder-changes')).toBeHidden();
  await page.locator('#ladder-pick summary').click();
  await expect(page.locator('#ladder-pick .ladder-changes li')).toHaveCount(3);
  await expect(page.locator('#ladder-pick .ladder-changes li').nth(0)).toContainText('Трудных боёв');
  await expect(page.locator('#ladder-pick [data-action="ladder-up"]')).toBeDisabled();
  expect(await noScroll(page)).toBe(true);
  await page.screenshot({ path: 'artifacts/forest-map-ladder-title.png' });
  await page.locator('#ladder-pick [data-action="ladder-down"]').click();
  await expect(page.locator('#ladder-value')).toHaveText('2');
  await page.locator('#run-start-button').click();
  await expect(page.locator('#map-screen')).toBeVisible();
  expect((await savedRun(page)).ladder).toBe(2);
  await expect(page.locator('#map-ladder')).toHaveText('Ступень 2');
  expect(await noScroll(page)).toBe(true);
  await page.screenshot({ path: 'artifacts/forest-map-ladder-map.png' });
  await expect(page.locator('#map-ladder')).toHaveAttribute('title', /1\. Трудных боёв.*\n2\. Случайные элиты/s);
  // A saved run on step 3 right before the Chief: the victory shows the step and opens step 4 in the profile.
  await page.evaluate(([key, value]) => localStorage.setItem(key, value), [RUN_KEY, serializeForestRun(walk([...TO_JAILER, 'camp-battle', 'camp-rest', 'camp-elite', 'camp-breakthrough'], 5, 4242, 3))]);
  await page.reload();
  await expect(page.locator('#run-start-button')).toContainText('ступень 3');
  await page.locator('#run-start-button').click();
  await expect(page.locator('#map-ladder')).toHaveText('Ступень 3');
  await node(page, 'camp-chief').click(); await settled(page);
  expect((await state(page)).runNode.ladder).toBe(3);
  await page.evaluate(() => (window as any).__PUZZLE_GAME.winLevel());
  await expect(page.locator('#modal')).toContainText('Главарь повержен');
  await expect(page.locator('#run-ladder')).toContainText('3');
  await expect(page.locator('#ladder-opened')).toContainText('Открыта ступень клятвы 4');
  expect((await profile()).ladder).toBe(4);
  await page.waitForTimeout(400);
  await page.screenshot({ path: 'artifacts/forest-map-ladder-victory.png' });
  // A new run from the result starts on the newly opened (highest) step.
  await page.locator('#modal [data-action="run-new"]').click();
  expect((await savedRun(page)).ladder).toBe(4);
  const journal = await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? 'null'), JOURNAL_KEY);
  expect(journal.attempts.at(-1)).toMatchObject({ key: 'run:chief-breakfast', nodeId: 'camp-chief', outcome: 'win', ladder: 3 });
  expect(errors).toEqual([]);
});

test('Jailer victory opens the spin and offers oaths; a hard-battle victory offers talismans; badges beside HP show name and effect', async ({ page }) => {
  test.setTimeout(60_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await seedRun(page, walk([...TRUNK, 'beast-wolf', 'beast-boar', 'trail-find', 'trail-banners']));
  await page.goto('/'); await page.locator('#run-start-button').click();
  await node(page, 'jailer').hover();
  await expect(page.locator('#map-detail')).toContainText('После победы открывает: Круговой удар');
  await expect(page.locator('#map-detail')).toContainText('клятва');
  await node(page, 'jailer').click(); await settled(page);
  await page.evaluate(() => (window as any).__PUZZLE_GAME.winLevel());
  await expect(page.locator('#modal')).toContainText('Открыто: Круговой удар');
  await page.locator('#modal [data-action="run-talisman"]').click();
  // The oath choice: three oaths and a refusal; a reload offers the same choice.
  await expect(page.locator('#modal [data-talisman]')).toHaveCount(3);
  await expect(page.locator('#modal [data-action="talisman-refuse"]')).toBeVisible();
  expect((await savedRun(page)).pending).toMatchObject({ kind: 'talisman', nodeId: 'jailer', source: 'oath' });
  await page.screenshot({ path: 'artifacts/forest-map-oath.png' });
  await page.reload(); await page.locator('#run-start-button').click();
  await expect(page.locator('#modal [data-talisman]')).toHaveCount(3);
  await page.locator('#modal [data-talisman="oath-wrath"]').click();
  await expect(page.locator('#map-screen')).toBeVisible();
  await expect(page.locator('#map-notice')).toContainText('Клятва ярости');
  await expect(page.locator('#map-tools')).toContainText('Круговой удар');
  // The oath's badge beside HP; hovering it shows the name and the effect line.
  const oath = page.locator('#map-talismans [data-talisman-badge="oath-wrath"]');
  await expect(oath).toBeVisible();
  await oath.hover();
  await expect(oath.locator('.talisman-tip')).toBeVisible();
  await expect(oath.locator('.talisman-tip')).toContainText('Клятва ярости');
  await expect(oath.locator('.talisman-tip')).toContainText('+2 энергии в начале каждого боя');
  await page.screenshot({ path: 'artifacts/forest-map-badges.png' });
  expect((await savedRun(page)).talismans).toEqual(['oath-wrath']);
  const journal = await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? 'null'), JOURNAL_KEY);
  expect(journal.runTalismans.at(-1)).toMatchObject({ nodeId: 'jailer', source: 'oath', chosen: 'oath-wrath' });
  expect(journal.runTalismans.at(-1).offered).toHaveLength(3);
  // The oath adds 2 energy at the start of the next battle.
  const energy = (await savedRun(page)).resources.player.energy;
  await node(page, 'den-battle').click(); await settled(page);
  expect((await state(page)).player.energy).toBe(Math.min(7, energy + 2));
  await expect(page.locator('#talisman-row [data-talisman-badge="oath-wrath"]')).toBeVisible();
  await page.evaluate(() => (window as any).__PUZZLE_GAME.winLevel());
  await page.locator('#modal [data-action="run-map"]').click();
  // A rest always comes right before a hard battle.
  await expect(node(page, 'den-elite')).toHaveAttribute('data-status', 'locked');
  await node(page, 'den-rest').click();
  await page.locator('#modal [data-action="rest-heal"]').click();
  await page.locator('#modal [data-action="resume"]').click();
  await node(page, 'den-elite').hover();
  await expect(page.locator('#map-detail')).toContainText('талисман');
  await node(page, 'den-elite').click(); await settled(page);
  // A wounded cat gets +1 HP for the hard battle (FOREST_HARD_HEAL): shown in the result and kept by the run.
  await page.evaluate(() => (window as any).__PUZZLE_GAME.damagePlayer(2));
  await page.evaluate(() => (window as any).__PUZZLE_GAME.winLevel());
  await expect(page.locator('#hard-heal')).toContainText('+1 HP за трудный бой');
  await expect(page.locator('#modal .result-stats')).toContainText('4/5');
  expect((await savedRun(page)).resources.player.hp).toBe(4);
  await expect(page.locator('#modal [data-action="run-talisman"]')).toContainText('ВЫБРАТЬ ТАЛИСМАН');
  const pending = (await savedRun(page)).pending;
  expect(pending).toMatchObject({ kind: 'talisman', nodeId: 'den-elite', source: 'hard' });
  await page.locator('#modal [data-action="run-talisman"]').click();
  await expect(page.locator('#modal [data-talisman]')).toHaveCount(3);
  await page.screenshot({ path: 'artifacts/forest-map-talisman.png' });
  await page.locator(`#modal [data-talisman="${pending.options[0]}"]`).click();
  await expect(page.locator('#map-screen')).toBeVisible();
  await expect(node(page, 'den-elite')).toHaveAttribute('data-status', 'current');
  await expect(node(page, 'den-breakthrough')).toHaveAttribute('data-status', 'available');
  const run = await savedRun(page);
  expect(run.pending).toBeNull(); expect(run.talismans).toEqual(['oath-wrath', pending.options[0]]); expect(run.finds).toHaveLength(1);
  await expect(page.locator('#map-talismans .talisman-badge')).toHaveCount(2);
  expect(await noScroll(page)).toBe(true);
  expect(errors).toEqual([]);
});

test('talisman forecast: the whetstone line and «смертельно — оберег спасёт» while the chain is held; the ward crumbles as forecast', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.evaluate(() => (window as any).__PUZZLE_GAME.startNodeBattle('wolf-ford', { row: 6, talismans: ['whetstone', 'ash-ward'], wardReady: true, player: { hp: 1, maxHp: 5, energy: 0 } }));
  await settled(page);
  await expect(page.locator('#talisman-row .talisman-badge')).toHaveCount(2);
  const ward = page.locator('#talisman-row [data-talisman-badge="ash-ward"]');
  await ward.hover();
  await expect(ward.locator('.talisman-tip')).toContainText('Пепельный оберег');
  // A move whose damage would kill the cat at 1 HP; the ward takes it.
  const path: number[] = await page.evaluate(() => { const game = (window as any).__PUZZLE_GAME; return (game.availableMoves() as number[][]).find(move => { const preview = game.preview(move); return preview.wardSaves && !preview.playerDies; }) ?? []; });
  expect(path.length).toBeGreaterThan(0);
  const first = await center(page, path[0]);
  await page.mouse.move(first.x, first.y); await page.mouse.down();
  for (const index of path.slice(1)) { const point = await center(page, index); await page.mouse.move(point.x, point.y, { steps: 4 }); }
  await expect.poll(async () => (await state(page)).chain).toEqual(path);
  await expect(page.locator('#chain-reward')).toContainText('Точильный камень: +1 к запасу');
  await expect(page.locator('#risk-preview')).toContainText('смертельно — оберег спасёт');
  await page.screenshot({ path: 'artifacts/talisman-forecast.png' });
  await page.mouse.up(); await settled(page);
  const after = await state(page);
  expect(after.player.hp).toBe(1); expect(after.player.ward).toBeFalsy(); expect(after.phase).not.toBe('LOSE');
  await expect(ward).toHaveClass(/spent/);
  // The first chain is done: the next one has no whetstone line.
  const next: number[] = await page.evaluate(() => ((window as any).__PUZZLE_GAME.availableMoves() as number[][])[0] ?? []);
  if (next.length && after.phase === 'PLAYER_INPUT') {
    const point = await center(page, next[0]);
    await page.mouse.move(point.x, point.y); await page.mouse.down();
    await expect.poll(async () => (await state(page)).chain.length).toBe(1);
    await expect(page.locator('#chain-reward')).not.toContainText('Точильный камень');
    await page.keyboard.press('Escape'); await page.mouse.up();
  }
  expect(errors).toEqual([]);
});

test('a map event is chosen by mouse: outcomes shown in advance, an unaffordable option says why, a reload keeps the event, telemetry records the choice', async ({ page }) => {
  test.setTimeout(60_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); failOnDialog(page);
  // The goblin barricade to the shaman with 0 energy: row 8 offers the banners or the goblin cache.
  await seedRun(page, walk([...TRUNK, 'goblin-archer', 'goblin-shield', 'goblin-shaman']));
  await page.goto('/'); await page.locator('#run-start-button').click();
  await expect(node(page, 'trail-cache')).toHaveAttribute('data-status', 'available');
  await expect(node(page, 'trail-banners')).toHaveAttribute('data-status', 'available');
  await expect(node(page, 'trail-brook')).toHaveAttribute('data-status', 'locked');
  await expect(node(page, 'trail-cache')).toContainText('?');
  await node(page, 'trail-cache').hover();
  await expect(page.locator('#map-detail')).toContainText('Событие');
  await expect(page.locator('#map-detail')).toContainText('Взломать, Разобрать осторожно, Пройти мимо');
  expect(await noScroll(page)).toBe(true);
  await node(page, 'trail-cache').click();
  // The event window: title, scene, three options with their outcomes; careful needs energy the cat has not.
  await expect(page.locator('#modal-title')).toHaveText('Гоблинский тайник');
  const choices = page.locator('#modal .event-choice');
  await expect(choices).toHaveCount(3);
  await expect(choices.nth(0).locator('.event-outcome').nth(0)).toContainText('50%');
  await expect(choices.nth(0).locator('.event-outcome').nth(0)).toContainText('добыча, 2 ресурса крафта');
  await expect(choices.nth(0).locator('.event-outcome').nth(1)).toContainText('50%');
  await expect(choices.nth(0).locator('.event-outcome').nth(1)).toContainText('ловушка, −2 HP (не ниже 1)');
  await expect(choices.nth(1)).toBeDisabled();
  await expect(choices.nth(1).locator('.event-reason')).toContainText('Нужна энергия: 1 (сейчас 0)');
  await expect(choices.nth(2)).toContainText('ничего не меняется');
  expect(await page.evaluate(() => { const box = document.querySelector('#modal')!.getBoundingClientRect(); return box.top >= 0 && box.bottom <= innerHeight; })).toBe(true);
  await page.waitForTimeout(400);
  await page.screenshot({ path: 'artifacts/forest-map-event.png' });
  expect(await savedRun(page)).toMatchObject({ pending: { kind: 'event', nodeId: 'trail-cache' } });
  // A disabled option does nothing.
  await choices.nth(1).click({ force: true });
  expect((await savedRun(page)).pending).toMatchObject({ kind: 'event' });
  // A reload brings back the same event.
  await page.reload();
  await page.locator('#run-start-button').click();
  await expect(page.locator('#modal-title')).toHaveText('Гоблинский тайник');
  await expect(page.locator('#modal .event-choice').nth(1)).toBeDisabled();
  const before = (await savedRun(page)).resources;
  await page.locator('#modal .event-choice').nth(0).click();
  await expect(page.locator('#event-result')).toContainText('Взломать');
  const after = await savedRun(page);
  expect(after).toMatchObject({ currentNodeId: 'trail-cache', pending: null, eventChoices: [{ nodeId: 'trail-cache', option: 'break' }] });
  const trap = after.eventChoices[0].outcome === 1;
  if (trap) { await expect(page.locator('#event-result')).toContainText('ловушка'); expect(after.resources.player.hp).toBe(Math.max(1, before.player.hp - 2)); }
  else { await expect(page.locator('#event-result')).toContainText('добыча'); expect(Object.values(after.resources.materials).reduce((a: number, b: any) => a + b, 0)).toBe(2); }
  await page.locator('#modal [data-action="run-map"]').click();
  await expect(node(page, 'trail-cache')).toHaveAttribute('data-status', 'current');
  await expect(node(page, 'jailer')).toHaveAttribute('data-status', 'available');
  await expect(page.locator('#map-battles')).toContainText('7');
  const events = (await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? 'null'), JOURNAL_KEY)).runEvents;
  expect(events).toHaveLength(1);
  expect(events[0]).toMatchObject({ nodeId: 'trail-cache', option: 'break', outcome: after.eventChoices[0].outcome });
  expect(errors).toEqual([]);
});
/**
 * A generated run standing right before its first merchant: battles won with the entry resources, the first one leaving
 * `loot` resources (elite loot) and the cat at `hp`; events take their first option without resources or HP.
 */
function beforeShop(seed: number, loot: Record<string, number>, hp: number): { run: ForestRunState; shop: string } {
  let run = createForestRun(seed, { map: 'generated', skipTrunk: true });
  const map = forestRunMap(run), shop = map.nodes.find(entry => entry.type === 'shop')!.id;
  const reaches = (id: string): boolean => id === shop || map.node(id)!.next.some(reaches);
  let looted = false;
  for (let guard = 0; guard < 40; guard++) {
    if (run.pending?.kind === 'battle') {
      const entry = run.pending.entry;
      run = ok(resolveBattle(run, { nodeId: run.pending.nodeId, won: true, player: { ...entry.player, hp }, inventory: { ...entry.inventory }, ...looted ? {} : { materials: { dew: 0, powder: 0, resin: 0, herbs: 0, ...loot } } }));
      looted = true;
    }
    if (run.pending?.kind === 'talisman') run = ok(chooseTalisman(run, null));
    if (run.pending?.kind === 'find') run = ok(chooseFindItem(run, run.pending.options[0]));
    if (run.pending?.kind === 'rest') run = ok(restHeal(run));
    if (run.pending?.kind === 'event') { const view = eventView(run)!; run = ok(chooseEventOption(run, view.options.find(option => option.available && /ничего|энерги|Холод/.test(option.outcomes.map(o => o.text).join()))?.id ?? view.options.find(option => option.available)!.id)); }
    if (run.pending?.kind === 'shop') run = ok(shopLeave(run));
    if (run.pending) continue;
    const next = availableNodes(run);
    if (next.some(node => node.id === shop)) return { run, shop };
    run = ok(enterNode(run, next.find(node => reaches(node.id))!.id));
  }
  throw new Error(`${seed}: the merchant is not reached`);
}

test('the merchant by mouse: goods with prices in 1280x720, a short stock says why, healing cut to the stock, a reload keeps the visit, leaving is recorded', async ({ page }) => {
  test.setTimeout(60_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); failOnDialog(page);
  // 4 resources (3 dew, 1 resin) and a wounded cat: a consumable (3) is affordable, the talisman and «Закалка» (4+) only as their prices allow.
  const { run, shop } = beforeShop(Math.imul(1, 2654435761) >>> 0, { dew: 3, resin: 1 }, 2);
  await seedRun(page, run);
  await page.goto('/'); await page.locator('#run-start-button').click();
  await expect(node(page, shop)).toHaveAttribute('data-status', 'available');
  await expect(node(page, shop)).toContainText('⚖');
  await node(page, shop).hover();
  await expect(page.locator('#map-detail')).toContainText('Торговец');
  await expect(page.locator('.map-legend')).toContainText('Торговец');
  await node(page, shop).click();
  await expect(page.locator('#modal .eyebrow')).toHaveText('ТОРГОВЕЦ');
  await expect(page.locator('#shop-stock')).toContainText('Ресурсы: 4');
  const goods = page.locator('#modal .shop-good');
  const count = await goods.count();
  expect(count).toBeGreaterThanOrEqual(4);
  expect(await page.evaluate(() => { const box = document.querySelector('#modal')!.getBoundingClientRect(); return box.top >= 0 && box.bottom <= innerHeight; })).toBe(true);
  await page.waitForTimeout(400);
  await page.screenshot({ path: 'artifacts/forest-map-shop.png' });
  // «Закалка» costs 4: affordable; buying a consumable first (3) leaves 1 — then «Закалка» says why it is out of reach.
  await expect(page.locator('#modal [data-shop-buy="item:0"]')).toContainText('КУПИТЬ · 3');
  await page.locator('#modal [data-shop-buy="item:0"]').click();
  await expect(page.locator('#shop-stock')).toContainText('Ресурсы: 1');
  await expect(page.locator('#modal [data-shop-buy="item:0"]')).toBeDisabled();
  await expect(page.locator('#modal [data-good="harden"] .event-reason')).toContainText('Нужно ресурсов: 4, есть 1');
  // Healing: the price of 2 is cut to the 1 resource left.
  await expect(page.locator('#modal [data-shop-buy="heal"]')).toContainText('1');
  const hp = (await savedRun(page)).resources.player.hp;
  await page.locator('#modal [data-shop-buy="heal"]').click();
  await expect(page.locator('#shop-stock')).toContainText('Ресурсы: 0');
  expect((await savedRun(page)).resources.player.hp).toBe(hp + 1);
  // The second HP is free with an empty stock.
  await expect(page.locator('#modal [data-shop-buy="heal"]')).toContainText('ДАРОМ');
  // A reload brings back the same merchant with the same purchases.
  await page.reload();
  await page.locator('#run-start-button').click();
  await expect(page.locator('#modal .eyebrow')).toHaveText('ТОРГОВЕЦ');
  await expect(page.locator('#modal [data-shop-buy="item:0"]')).toContainText('КУПЛЕНО');
  await page.locator('#modal [data-shop-buy="heal"]').click();
  expect((await savedRun(page)).resources.player.hp).toBe(Math.min(5, hp + 2));
  await page.locator('#modal [data-action="shop-leave"]').click();
  await expect(node(page, shop)).toHaveAttribute('data-status', 'current');
  await expect(page.locator('#map-notice')).toContainText('покупок — 3');
  const saved = await savedRun(page);
  expect(saved.shops).toHaveLength(1);
  expect(saved.shops[0].bought.map((purchase: { good: string }) => purchase.good)).toEqual(['item', 'heal', 'heal']);
  const journal = await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? 'null'), JOURNAL_KEY);
  expect(journal.runShops.at(-1)).toMatchObject({ nodeId: shop, bought: [{ good: 'item', price: 3 }, { good: 'heal', price: 2 }, { good: 'heal', price: 2 }] });
  expect(errors).toEqual([]);
});

test('rest clears effects on the cat and says so', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  let run = ok(enterNode(walk(TRUNK), 'beast-wolf'));
  run = ok(resolveBattle(run, { nodeId: 'beast-wolf', won: true, player: { hp: 3, maxHp: 5, energy: 1, damageEffects: { burning: 2 } }, inventory: { ...run.resources.inventory } }));
  await seedRun(page, run);
  await page.goto('/'); await page.locator('#run-start-button').click();
  await expect(page.locator('#map-hp .map-effects')).toContainText('Горение ×2');
  await node(page, 'trail-rest').click();
  await expect(page.locator('#rest-heal')).toContainText('снимет эффекты');
  await page.locator('#modal [data-action="rest-heal"]').click();
  await expect(page.locator('#rest-copy')).toContainText('Вылечено: 2 HP');
  await expect(page.locator('#rest-copy')).toContainText('Эффекты на коте сняты');
  await page.locator('#modal [data-action="resume"]').click();
  await expect(page.locator('#map-hp .map-effects')).toHaveCount(0);
  expect((await savedRun(page)).resources.player.damageEffects).toBeUndefined();
  // The playtest journal records the rest: heal, 2 HP.
  const journal = await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? 'null'), JOURNAL_KEY);
  expect(journal.runRests.at(-1)).toMatchObject({ nodeId: 'trail-rest', choice: 'heal', healed: 2, crafted: [] });
  expect(errors).toEqual([]);
});

test('rest crafting by mouse: several recipes, the heal goes away, a reload keeps the open rest, a closed item opens for the next battle', async ({ page }) => {
  test.setTimeout(60_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); failOnDialog(page);
  // The goblin route without a find; the camp battle left 5 dew and 2 powder (elite loot), the cat at 3 HP.
  let run = ok(enterNode(walk([...TRUNK, 'goblin-archer', 'goblin-shield', 'goblin-shaman', 'trail-banners', 'jailer']), 'camp-battle'));
  run = ok(resolveBattle(run, { nodeId: 'camp-battle', won: true, player: { hp: 3, maxHp: 5, energy: run.resources.player.energy }, inventory: { ...run.resources.inventory },
    materials: { dew: 5, powder: 2, resin: 0, herbs: 0 } }));
  expect(run.tools.items).not.toContain('bomb');
  await seedRun(page, run);
  await page.goto('/'); await page.locator('#run-start-button').click();
  await expect(page.locator('#map-tools [data-resource="dew"]')).toContainText('×5');
  await node(page, 'camp-rest').click();
  const dew = page.locator('#modal [data-craft="dew"]'), powder = page.locator('#modal [data-craft="powder"]');
  await expect(page.locator('#rest-heal [data-action="rest-heal"]')).toBeEnabled();
  await expect(page.locator('#modal [data-recipe="powder"]')).toContainText('откроет');
  await expect(page.locator('#modal [data-craft="resin"]')).toBeDisabled();
  await expect(page.locator('#modal [data-action="rest-finish"]')).toHaveCount(0);
  await page.waitForTimeout(400);
  await page.screenshot({ path: 'artifacts/forest-map-rest-choice.png', animations: 'disabled' });
  await dew.click();
  await expect(page.locator('#rest-crafted')).toContainText('Холод ×1');
  await expect(page.locator('#rest-heal [data-action="rest-heal"]')).toBeDisabled();
  await expect(page.locator('#rest-heal')).toContainText('Выбран крафт');
  await dew.click();
  await expect(page.locator('#rest-crafted')).toContainText('Холод ×2');
  await expect(dew).toBeDisabled();
  await expect(page.locator('#modal [data-recipe="dew"] .rest-have')).toHaveText('1');
  await powder.click();
  await expect(page.locator('#rest-crafted')).toContainText('Бомба ×1');
  await page.waitForTimeout(400);
  await page.screenshot({ path: 'artifacts/forest-map-rest-craft.png' });
  // A reload restores the same open rest: the crafts, the spent resources, no heal.
  await page.reload(); await page.locator('#run-start-button').click();
  await expect(page.locator('#rest-crafted')).toContainText('Холод ×2');
  await expect(page.locator('#rest-crafted')).toContainText('Бомба ×1');
  await expect(page.locator('#rest-heal [data-action="rest-heal"]')).toBeDisabled();
  await expect(dew).toBeDisabled();
  await page.locator('#modal [data-action="rest-finish"]').click();
  await expect(page.locator('#map-notice')).toContainText('создано');
  await expect(page.locator('#map-tools')).toContainText('Бомба ×1');
  const saved = await savedRun(page);
  expect(saved.pending).toBeNull();
  expect(saved.resources.player.hp).toBe(3);
  expect(saved.resources.materials).toEqual({ dew: 1, powder: 0, resin: 0, herbs: 0 });
  expect(saved.rests.at(-1)).toEqual({ nodeId: 'camp-rest', choice: 'craft', crafted: ['frost', 'frost', 'bomb'] });
  const journal = await page.evaluate(key => JSON.parse(localStorage.getItem(key) ?? 'null'), JOURNAL_KEY);
  expect(journal.runRests.at(-1)).toMatchObject({ nodeId: 'camp-rest', choice: 'craft', healed: 0, crafted: ['frost', 'frost', 'bomb'] });
  // The bomb crafted here is open in the next battle.
  await node(page, 'camp-elite').click(); await settled(page);
  expect((await state(page)).runNode.allowedItems).toContain('bomb');
  expect((await state(page)).inventory.bomb).toBe(1);
  await expect(page.locator('#bomb-button')).toBeEnabled();
  expect(errors).toEqual([]);
});

/** Start a node battle straight on the engine (src/game stays untouched): the run's opened tools are given by the setup. */
async function startNodeBattle(page: Page, template: object, allowedAbilities: string[], allowedItems: string[]) {
  await page.evaluate(([template, allowedAbilities, allowedItems]) => {
    const engine = (window as any).__PUZZLE_GAME.engine;
    const ok = engine.startRunBattle({ nodeId: 'trunk-1', label: 'Проба', seed: 4242, template, player: { hp: 5, maxHp: 5, energy: 2 },
      inventory: { frost: 1, bomb: 0, healing: 0, fire: 0 }, allowedItems, allowedAbilities });
    if (!ok) throw new Error('startRunBattle failed');
  }, [template, allowedAbilities, allowedItems] as const);
  await settled(page);
}

test('a registry battle: help opens, marked targets are counted, an opened jump is visible', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); failOnDialog(page);
  await page.goto('/');
  await page.locator('#run-start-button').click();
  await node(page, 'trunk-1').click(); await settled(page);
  // A registry battle is started on the engine with the tools of a run that opened the jump.
  await startNodeBattle(page, { kind: 'battle', id: 'wolf-ford' }, ['jump'], ['frost']);
  await expect(page.locator('#game-screen')).toHaveClass(/tutorial-abilities/);
  await expect(page.locator('.energy-hud')).toBeVisible();
  await expect(page.locator('.ability-button[data-ability="jump"]')).toBeVisible();
  await expect(page.locator('.ability-button[data-ability="jump"]')).toBeEnabled();
  await expect(page.locator('.item-button[data-item="frost"]')).toBeVisible();
  await expect(page.locator('#objectives')).toContainText('Отмеченные охранники');
  await expect(page.locator('#objectives')).toContainText('0 / 4');
  await expect(page.locator('#tutorial-message')).toContainText('Волк рядом с живым волком');
  await expect(page.locator('.field-guide')).toContainText('Прыжок');
  await expect(page.locator('.field-guide')).toContainText('Холод');
  await page.screenshot({ path: 'artifacts/forest-map-registry-battle.png' });
  await page.locator('[data-action="help"]').first().click();
  await expect(page.locator('#modal')).toContainText('Вожак у брода');
  await expect(page.locator('#modal')).toContainText('ПОХОД');
  await page.locator('#modal [data-action="resume"]').click();
  // Without opened tools the abilities panel and energy stay hidden.
  await startNodeBattle(page, { kind: 'battle', id: 'wolf-ford' }, [], []);
  await expect(page.locator('#game-screen')).not.toHaveClass(/tutorial-abilities/);
  await expect(page.locator('.energy-hud')).toBeHidden();
  await expect(page.locator('.field-guide')).not.toContainText('Прыжок');
  expect(errors).toEqual([]);
});

test('a trunk node uses the run tools: an opened jump is available in the first trunk battle', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); failOnDialog(page);
  await page.goto('/');
  await page.locator('#run-start-button').click();
  await node(page, 'trunk-1').click(); await settled(page);
  expect((await state(page)).tutorial.allowedAbilities).toEqual([]);
  await expect(page.locator('#game-screen')).not.toHaveClass(/tutorial-abilities/);
  await expect(page.locator('.energy-hud')).toBeHidden();
  await startNodeBattle(page, { kind: 'battle', id: 'trunk-wake' }, ['jump'], ['frost']);
  await expect(page.locator('#game-screen')).toHaveClass(/tutorial-abilities/);
  await expect(page.locator('.energy-hud')).toBeVisible();
  await expect(page.locator('.ability-button[data-ability="jump"]')).toBeVisible();
  await expect(page.locator('.ability-button[data-ability="jump"]')).toBeEnabled();
  await expect(page.locator('.field-guide')).toContainText('Прыжок');
  await page.locator('[data-action="help"]').first().click();
  await expect(page.locator('#modal')).toContainText('ПОХОД');
  await page.locator('#modal [data-action="resume"]').click();
  expect(errors).toEqual([]);
});

test('registry battle end to end: the beast trail node from the map, a real mouse route, the result on the map', async ({ page }) => {
  test.setTimeout(60_000);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); failOnDialog(page);
  // Run seed 1: the authored route of wolf-ford is checked for it in src/game/beastBattles.spec.ts.
  await seedRun(page, walk(TRUNK, 5, 1));
  await page.goto('/'); await page.locator('#run-start-button').click();
  await node(page, 'beast-wolf').hover();
  await expect(page.locator('#map-detail')).toContainText('Вожак у брода');
  await expect(page.locator('#map-detail')).not.toContainText('временно');
  await node(page, 'beast-wolf').click(); await settled(page);
  const entry = await state(page);
  expect(entry.runNode.nodeId).toBe('beast-wolf'); expect(entry.board.filter((cell: any) => cell?.variant === 'wolf').length).toBeGreaterThan(1);
  await expect(page.locator('#chapter-number')).toContainText('ПОХОД');
  await expect(page.locator('#objectives')).toContainText('0 / 4');
  const cell = (label: string) => (Number(label.slice(1)) - 1) * entry.cols + label.charCodeAt(0) - 65;
  await draw(page, ['B5', 'C5', 'C4', 'D3', 'D2'].map(cell));
  expect((await state(page)).phase).toBe('PLAYER_INPUT');
  // The goals open the door C1; the same chain finishes C2 and enters it (02.10.2026: victory only through the exit).
  await draw(page, ['C3', 'D4', 'E3', 'E2', 'D1', 'C2', 'C1'].map(cell));
  expect((await state(page)).phase).toBe('WIN');
  await expect(page.locator('#modal [data-action="run-map"]')).toBeVisible();
  await page.locator('#modal [data-action="run-map"]').click();
  await expect(node(page, 'beast-wolf')).toHaveAttribute('data-status', 'current');
  await expect(node(page, 'beast-boar')).toHaveAttribute('data-status', 'available');
  await expect(node(page, 'trail-rest')).toHaveAttribute('data-status', 'available');
  const run = await savedRun(page);
  expect(run.visited).toEqual([...TRUNK, 'beast-wolf']); expect(run.pending).toBeNull();
  expect(run.tools.items).toContain('frost');
  await expect(page.locator('#map-battles')).toContainText('5');
  expect(errors).toEqual([]);
});
