/**
 * Forest-map run model (design: docs/biomes/forest-map.md). Pure logic without DOM or engine:
 * every command takes a run state and returns a new one plus events for the map screen.
 * Battles are played by ForestEngine.startRunBattle(battleSetup(run)); the finished battle is fed back
 * with resolveBattle(run, engine.runBattleOutcome()).
 */
import { ITEM_KINDS, mixSeed, rewardChoices } from '../items';
import type { LootKind, ResourceKind, AbilityKind, ItemKind } from '../forestTypes';
import { RUN_PRESSURE_FIRST_ROW } from '../mapBattleRules';
import { CHEST_RESOURCES } from '../exitRules';
import { CRAFT_COST, craftSource, emptyMaterials, isResource, RESOURCE_KINDS, RESOURCES } from '../resources';
import { AUTHORED_RUN_MAP, nodeBattleTemplate, hasVictoryFind, isBattleNode, isTrunkNode, nodeRefillPalette, type ForestMapNode, type ForestNodeGrant, type ForestRunMap, FOREST_HARD_HEAL } from './forestMap';
import type { RunBattleOutcome, RunBattleSetup, RunBattleTemplate, RunPlayerResources } from './runBattle';
import { forestBattle } from './forestBattles';
import { eventOption, forestEvent, optionEnergyCost, optionHpCost, describeOutcome, FOREST_EVENTS, type EventOption, type ForestEvent } from './forestEvents';
import { generatedRunMap, generateForestMap, validateStoredMap, type GeneratedForestMap } from './mapGenerator';
import { battlePoolEntry, pickPoolBattle, poolCandidates, type PoolBattleType } from './battlePools';

/**
 * Version 2 (04.10.2026): the run carries its map (`map`) and the battles and events taken from pools (`picks`).
 * Version 1 saves walk the authored graph and load as version 2 with `map: { kind: 'authored' }`.
 */
export const FOREST_RUN_VERSION = 2;
/** Same caps as the battle engine: 5 HP in built-in modes, energy up to 7. */
export const FOREST_RUN_START_HP = 5;
const MAX_ENERGY = 7;
const ABILITY_KINDS: AbilityKind[] = ['jump', 'spin'];

/** `materials`: crafting resources (elite loot, chests, events; resources.ts), spent at rests; absent until the first. */
export interface ForestRunResources { player: RunPlayerResources; inventory: Record<ItemKind, number>; materials?: Record<ResourceKind, number> }
/** Tools opened by run events (grants and finds); a map battle allows only these. */
export interface ForestRunTools { items: ItemKind[]; abilities: AbilityKind[] }
export type ForestRunPending =
  /**
   * Entered battle node. `entry` is the snapshot on entering: the battle starts from it (also after a reload, the
   * battle in progress is not saved). A defeat ends the run (decision of 04.10.2026, docs/roguelike-runs.md);
   * saves made before that may still carry a `defeats` counter, which parseForestRun drops.
   */
  | { kind: 'battle'; nodeId: string; seed: number; entry: ForestRunResources; tools: ForestRunTools }
  /** Item choice of a find node, or the reward of a won hard battle (the node completes after the choice). */
  | { kind: 'find'; nodeId: string; options: ItemKind[] }
  /** Entered event node (forestEvents.ts): its options wait for a choice; a reload offers the same event. */
  | { kind: 'event'; nodeId: string }
  /**
   * Entered rest node (decision of 04.10.2026): heal or craft. Healing completes the rest at once; `crafted` lists the
   * items crafted here so far (non-empty — the craft is chosen and healing is gone); restFinish completes it. A reload
   * offers the same rest with the same crafts.
   */
  | { kind: 'rest'; nodeId: string; crafted: ItemKind[] };
/** What a completed rest gave: healing, or crafted items (in crafting order). */
export interface ForestRunRest { nodeId: string; choice: 'heal' | 'craft'; crafted: ItemKind[] }
export type ForestRunResult =
  | { outcome: 'victory'; nodeId: string }
  /** The branch ends at a boss that is not implemented yet. This is not a victory. */
  | { outcome: 'boss-in-development'; nodeId: string }
  /** The cat fell in the battle of `nodeId` (an entered, not completed node): the run is over (decision of 04.10.2026). */
  | { outcome: 'defeat'; nodeId: string };

/**
 * The map of a run: the authored graph FOREST_MAP (saves before 04.10.2026 and tests) or a map generated by the run
 * seed (mapGenerator.ts). A generated map is kept whole in the save, so a later tuning of the generator never changes a
 * run in progress.
 */
export type ForestRunMapRef = { kind: 'authored' } | ({ kind: 'generated' } & GeneratedForestMap);
/** The battle or event a pool node of a generated map got on entering (battlePools.ts, forestEvents.ts). */
export interface ForestRunPick { nodeId: string; battleId?: string; eventId?: string }

export interface ForestRunState {
  version: typeof FOREST_RUN_VERSION;
  seed: number;
  map: ForestRunMapRef;
  /** Pool picks of the entered nodes of a generated map, in entering order (empty on the authored graph). */
  picks: ForestRunPick[];
  /** Last completed node; null before the first battle. */
  currentNodeId: string | null;
  /**
   * The run started past the trunk: the player profile says the trunk was cleared in an earlier run (decision of
   * 04.10.2026). The first transitions are the trunk exit's; trunk nodes are not in `visited`. Absent otherwise.
   */
  skippedTrunk?: true;
  /** Completed nodes in order. */
  visited: string[];
  /** Items taken on finds and hard-battle rewards, in visiting order; with `visited` it determines the opened tools. */
  finds: { nodeId: string; item: ItemKind }[];
  /**
   * Elite loot picked up in won battles (elite.ts): for a consumable the net gain over the battle's entry inventory,
   * for a resource the count the battle reports. With grants and finds it bounds what a saved run may hold: items
   * come only from authored elites (one each), resources also from random elites (rows from 5, unbounded). Absent in
   * saves before 01.10.2026.
   */
  loot: { nodeId: string; item: LootKind; count: number }[];
  /**
   * Choices made at events, in visiting order: the option id and the index of its outcome (rolled by the run seed and
   * the node id). With the event data they bound what an event may have added. Absent in saves before 04.10.2026.
   */
  eventChoices: { nodeId: string; option: string; outcome: number }[];
  /**
   * Completed rests, in visiting order: healing or the crafted items. With the resources gained before each rest they
   * bound what crafting spent and added. Absent in saves before 04.10.2026 (a rest healed on entering): read as healing.
   */
  rests: ForestRunRest[];
  resources: ForestRunResources;
  tools: ForestRunTools;
  /** Points of all finished node battles, the lost one included (the battle's `state.score`). Absent in saves before 04.10.2026: read as 0. */
  score: number;
  pending: ForestRunPending | null;
  result: ForestRunResult | null;
}

export type ForestRunEvent =
  /** `row`: map row of the entered node (the player profile marks the trunk cleared on the first row past it). */
  | { type: 'node-entered'; nodeId: string; row: number }
  | { type: 'tools-unlocked'; items: ItemKind[]; abilities: AbilityKind[] }
  | { type: 'items-granted'; items: Partial<Record<ItemKind, number>> }
  | { type: 'battle-ready'; nodeId: string }
  /** The node battle was lost: the run is over (`result.outcome === 'defeat'`). */
  | { type: 'run-lost'; nodeId: string }
  /** A rest waits for its choice: heal or craft. */
  | { type: 'rest-offered'; nodeId: string }
  /** One recipe at a rest: two `resource` became one `item` (a closed item also opens: `tools-unlocked`). */
  | { type: 'rest-crafted'; nodeId: string; resource: ResourceKind; item: ItemKind }
  /** The rest is over: what was chosen, HP healed (0 for a craft or at full HP) and the items crafted. */
  | { type: 'rest-completed'; nodeId: string; choice: 'heal' | 'craft'; healed: number; crafted: ItemKind[] }
  /** Rest heal, or the hard-battle victory heart (+1 HP); `amount` is 0 at full HP. */
  | { type: 'healed'; nodeId: string; amount: number }
  /** Rest removed burning, poison and bleeding from the cat. */
  | { type: 'effects-cleared'; nodeId: string }
  | { type: 'find-offered'; nodeId: string; options: ItemKind[] }
  | { type: 'item-chosen'; nodeId: string; item: ItemKind }
  | { type: 'event-offered'; nodeId: string }
  /** The event option was taken: its rolled outcome and what really changed (HP and energy after the clamps). */
  | { type: 'event-resolved'; nodeId: string; option: string; outcome: number; text: string;
    changes: { hp: number; energy: number; items: Partial<Record<ItemKind, number>>; materials: ResourceKind[] } }
  | { type: 'node-completed'; nodeId: string }
  | { type: 'run-won'; nodeId: string }
  | { type: 'boss-in-development'; nodeId: string };

export type ForestRunStep = { ok: true; run: ForestRunState; events: ForestRunEvent[] } | { ok: false; reason: string };

const textHash = (text: string): number => {
  let hash = 0x811c9dc5;
  for (let n = 0; n < text.length; n++) hash = Math.imul(hash ^ text.charCodeAt(n), 0x01000193) >>> 0;
  return hash;
};
/** Deterministic node seed: the same run seed and node id always give the same battle, find or event outcome. */
export function forestNodeSeed(runSeed: number, nodeId: string): number {
  return mixSeed(runSeed >>> 0, textHash(nodeId));
}

/**
 * `skipTrunk`: the player profile marks the trunk as cleared, so the run starts at the trail fork.
 * `map`: `'generated'` — a map by the run seed (the game's runs, main.ts); `'authored'` (default) — the authored graph
 * FOREST_MAP, the source of the trunk and of the tests.
 */
export function createForestRun(seed: number, options: { skipTrunk?: boolean; map?: 'authored' | 'generated' } = {}): ForestRunState {
  const map: ForestRunMapRef = options.map === 'generated' ? { kind: 'generated', ...generateForestMap(seed) } : { kind: 'authored' };
  return {
    version: FOREST_RUN_VERSION, seed: seed >>> 0, map, picks: [], currentNodeId: null, ...options.skipTrunk ? { skippedTrunk: true as const } : {}, visited: [], finds: [], loot: [], eventChoices: [], rests: [], score: 0,
    resources: { player: { hp: FOREST_RUN_START_HP, maxHp: FOREST_RUN_START_HP, energy: 0 },
      inventory: { frost: 0, bomb: 0, healing: 0, fire: 0 } },
    tools: { items: [], abilities: [] }, pending: null, result: null,
  };
}

// ---------- The run's map and pool picks ----------

const mapCache = new WeakMap<object, ForestRunMap>();
/** The graph of a run (cached per stored map object). */
export function forestRunMap(run: Pick<ForestRunState, 'map'>): ForestRunMap {
  const ref = run.map;
  if (!ref || ref.kind !== 'generated') return AUTHORED_RUN_MAP;
  let map = mapCache.get(ref);
  if (!map) { map = generatedRunMap(ref); mapCache.set(ref, map); }
  return map;
}
/** A pool node shown with its pick: the battle's name, content and field feature, or the event's title and content. */
function withPick(node: ForestMapNode, pick: ForestRunPick | null | undefined): ForestMapNode {
  if (node.content.kind !== 'pool' || !pick) return node;
  if (pick.battleId) {
    const battle = forestBattle(pick.battleId), entry = battlePoolEntry(pick.battleId);
    return { ...node, name: battle?.name ?? node.name, content: { kind: 'battle', battleId: pick.battleId }, ...entry?.feature ? { feature: entry.feature } : {},
      ...entry?.placeholder ? { placeholder: { planned: entry.placeholder } } : {} };
  }
  if (pick.eventId) return { ...node, name: forestEvent(pick.eventId)?.title ?? node.name, content: { kind: 'event', eventId: pick.eventId } };
  return node;
}
/** A node of the run's map, with its pick once entered. Undefined for an id the map does not have. */
export function runNode(run: Pick<ForestRunState, 'map' | 'picks'>, id: string): ForestMapNode | undefined {
  const node = forestRunMap(run).node(id);
  return node && withPick(node, node.content.kind === 'pool' ? run.picks?.find(pick => pick.nodeId === id) : undefined);
}
const POOL_BATTLE_SALT = 0x5b1d7a3c, POOL_EVENT_SALT = 0x2e9f41d7;
/**
 * The pick a pool node gets if entered now: a battle of its row, type and lane with the tools open on entering it
 * (battlePools.ts: window of repeats, main enemy), or an event not met in this run. It depends on the run seed, the
 * node id and the battles and events already met — never on the map stream (the map is fixed by the seed).
 */
function nextPick(run: ForestRunState, node: ForestMapNode): ForestRunPick | null {
  if (node.content.kind !== 'pool') return null;
  const roll = (salt: number) => mixSeed(forestNodeSeed(run.seed, node.id), salt);
  if (node.type === 'event') {
    const met = run.picks.flatMap(pick => pick.eventId ? [pick.eventId] : []), ids = Object.keys(FOREST_EVENTS);
    const fresh = ids.filter(id => !met.includes(id)), list = fresh.length ? fresh : ids;
    return list.length ? { nodeId: node.id, eventId: list[roll(POOL_EVENT_SALT) % list.length] } : null;
  }
  const tools = { items: [...new Set([...run.tools.items, ...node.grants?.items ?? []])], abilities: [...new Set([...run.tools.abilities, ...node.grants?.abilities ?? []])] };
  const candidates = poolCandidates({ row: node.row, type: node.type as PoolBattleType, lane: node.lane }, tools);
  const battleId = pickPoolBattle(candidates, run.picks.flatMap(pick => pick.battleId ? [pick.battleId] : []), roll(POOL_BATTLE_SALT));
  return battleId ? { nodeId: node.id, battleId } : null;
}
/** A node as it would be entered now: an unentered pool node shows the battle or event it would get. */
function previewNode(run: ForestRunState, id: string): ForestMapNode | undefined {
  const node = runNode(run, id);
  return node?.content.kind === 'pool' ? withPick(node, nextPick(run, node)) : node;
}

/**
 * Transitions the player may choose now. Empty while a node is in progress or after the run ended. A pool node of a
 * generated map comes with the battle or event it would get (the choice of the next node shows what it holds).
 */
export function availableNodes(run: ForestRunState): ForestMapNode[] {
  if (run.pending || run.result) return [];
  const map = forestRunMap(run);
  const ids = run.currentNodeId === null ? map.starts(!!run.skippedTrunk) : map.node(run.currentNodeId)?.next ?? [];
  return ids.flatMap(id => { const node = previewNode(run, id); return node ? [node] : []; });
}

const fail = (reason: string): ForestRunStep => ({ ok: false, reason });

function completeNode(run: ForestRunState, node: ForestMapNode, events: ForestRunEvent[]) {
  run.visited.push(node.id); run.currentNodeId = node.id; run.pending = null;
  events.push({ type: 'node-completed', nodeId: node.id });
  if (node.type === 'boss') { run.result = { outcome: 'victory', nodeId: node.id }; events.push({ type: 'run-won', nodeId: node.id }); }
}

function unlock(tools: ForestRunTools, items: ItemKind[] = [], abilities: AbilityKind[] = [], events: ForestRunEvent[]) {
  const newItems = [...new Set(items)].filter(item => !tools.items.includes(item));
  const newAbilities = [...new Set(abilities)].filter(ability => !tools.abilities.includes(ability));
  tools.items.push(...newItems); tools.abilities.push(...newAbilities);
  if (newItems.length || newAbilities.length) events.push({ type: 'tools-unlocked', items: newItems, abilities: newAbilities });
}

function applyGrant(run: ForestRunState, grant: ForestNodeGrant, events: ForestRunEvent[]) {
  unlock(run.tools, grant.items, grant.abilities, events);
  const added = grant.inventory ?? {};
  for (const item of ITEM_KINDS) run.resources.inventory[item] += added[item] ?? 0;
  if (Object.keys(added).length) events.push({ type: 'items-granted', items: { ...added } });
}

/** Three items from the castle reward table; a find node (slot 0) and a hard-battle reward (slot 1) use separate rolls. */
function findOptions(runSeed: number, node: ForestMapNode): ItemKind[] {
  return rewardChoices(forestNodeSeed(runSeed, node.id), node.type === 'find' ? 0 : 1).map(option => option.item);
}
function offerFind(run: ForestRunState, nodeId: string, events: ForestRunEvent[]) {
  const options = findOptions(run.seed, runNode(run, nodeId)!);
  run.pending = { kind: 'find', nodeId, options };
  events.push({ type: 'find-offered', nodeId, options: [...options] });
}

/** Move to one of availableNodes(run). Applies the node's grant, then starts its battle, rest or find. */
export function enterNode(current: ForestRunState, nodeId: string): ForestRunStep {
  let node = runNode(current, nodeId);
  if (!node) return fail('Такого узла нет на карте.');
  if (current.result) return fail('Поход уже завершён.');
  if (current.pending) return fail('Сначала заверши текущий узел.');
  if (!availableNodes(current).some(entry => entry.id === nodeId)) return fail('Этот узел сейчас недоступен.');
  const run = structuredClone(current), events: ForestRunEvent[] = [{ type: 'node-entered', nodeId, row: node.row }];
  if (node.content.kind === 'pool') {
    // The battle or event of a generated node is taken from its pool now and kept for the run (and its save).
    const pick = nextPick(run, node);
    if (!pick) return fail('Для этого узла нет ни боя, ни события в пулах.');
    run.picks.push(pick); node = withPick(node, pick);
  }
  if (node.content.kind === 'in-development') {
    run.result = { outcome: 'boss-in-development', nodeId };
    events.push({ type: 'boss-in-development', nodeId }); return { ok: true, run, events };
  }
  if (node.grants) applyGrant(run, node.grants, events);
  if (node.content.kind === 'rest') {
    run.pending = { kind: 'rest', nodeId, crafted: [] }; events.push({ type: 'rest-offered', nodeId }); return { ok: true, run, events };
  }
  if (node.content.kind === 'find') { offerFind(run, nodeId, events); return { ok: true, run, events }; }
  if (node.content.kind === 'event') {
    run.pending = { kind: 'event', nodeId }; events.push({ type: 'event-offered', nodeId }); return { ok: true, run, events };
  }
  run.pending = { kind: 'battle', nodeId, seed: forestNodeSeed(run.seed, nodeId),
    entry: structuredClone(run.resources), tools: structuredClone(run.tools) };
  events.push({ type: 'battle-ready', nodeId }); return { ok: true, run, events };
}

/** Engine template of a battle node: its registry battle; null if the node has none. */
export function nodeRunTemplate(node: ForestMapNode): RunBattleTemplate | null {
  const { content } = node;
  return content.kind === 'battle' && forestBattle(content.battleId) ? { kind: 'battle', id: content.battleId } : null;
}

/** Engine setup for the entered battle node; the same run always yields the same setup (also after reload). */
export function battleSetup(run: ForestRunState): RunBattleSetup | null {
  const pending = run.pending; if (pending?.kind !== 'battle') return null;
  const node = runNode(run, pending.nodeId); if (!node) return null;
  const template = nodeRunTemplate(node);
  if (!template) return null;
  const entry = structuredClone(pending.entry);
  const paletteWeights = nodeRefillPalette(node);
  return { nodeId: node.id, label: node.name, seed: pending.seed, template, row: node.row, player: entry.player, inventory: entry.inventory,
    allowedItems: [...pending.tools.items], allowedAbilities: [...pending.tools.abilities], ...(paletteWeights ? { paletteWeights } : {}) };
}

const clampCount = (value: unknown) => typeof value === 'number' && Number.isFinite(value) ? Math.max(0, Math.floor(value)) : 0;

/**
 * Feed a finished battle back. Victory carries HP, energy, items and effects. Defeat ends the run: the result names the
 * lost node, the resources stay the entry snapshot (a living cat), and nothing more can be entered.
 */
export function resolveBattle(current: ForestRunState, outcome: RunBattleOutcome): ForestRunStep {
  const pending = current.pending;
  if (pending?.kind !== 'battle' || pending.nodeId !== outcome.nodeId) return fail('Этот бой не относится к текущему узлу.');
  const run = structuredClone(current), events: ForestRunEvent[] = [];
  const battle = run.pending as Extract<ForestRunPending, { kind: 'battle' }>;
  if (outcome.won && !(outcome.player.hp >= 1)) return fail('Победа с 0 HP невозможна.');
  run.score = (run.score ?? 0) + clampCount(outcome.score);
  if (!outcome.won) {
    run.pending = null; run.result = { outcome: 'defeat', nodeId: battle.nodeId };
    events.push({ type: 'run-lost', nodeId: battle.nodeId }); return { ok: true, run, events };
  }
  const maxHp = Math.max(1, clampCount(outcome.player.maxHp));
  run.resources = {
    player: { hp: Math.min(maxHp, clampCount(outcome.player.hp)), maxHp,
      energy: Math.min(MAX_ENERGY, Math.max(0, Number.isFinite(outcome.player.energy) ? outcome.player.energy : 0)),
      ...(outcome.player.damageEffects ? { damageEffects: { ...outcome.player.damageEffects } } : {}) },
    inventory: Object.fromEntries(ITEM_KINDS.map(item => [item, clampCount(outcome.inventory[item])])) as Record<ItemKind, number>,
  };
  // Items picked up in the battle (elite loot) raise the inventory over its entry snapshot; resources picked up are
  // added to the run's stock for crafting at rests.
  for (const item of ITEM_KINDS) {
    const count = run.resources.inventory[item] - battle.entry.inventory[item];
    if (count > 0) run.loot.push({ nodeId: battle.nodeId, item, count });
  }
  const materials = battle.entry.materials ? { ...battle.entry.materials } : undefined;
  for (const resource of RESOURCE_KINDS) {
    const count = clampCount(outcome.materials?.[resource] ?? 0);
    if (!count) continue;
    run.loot.push({ nodeId: battle.nodeId, item: resource, count });
    (run.resources.materials ??= { ...emptyMaterials(), ...materials })[resource] += count;
  }
  if (materials && !run.resources.materials) run.resources.materials = materials;
  const node = runNode(run, battle.nodeId)!;
  if (node.rewardGrants) applyGrant(run, node.rewardGrants, events);
  if (node.type === 'hard') {
    // The hard battle ends when its targets fall, so the heart is given with the victory, not picked up on a cell.
    const player = run.resources.player, amount = Math.max(0, Math.min(FOREST_HARD_HEAL, player.maxHp - player.hp));
    player.hp += amount; events.push({ type: 'healed', nodeId: node.id, amount });
  }
  if (hasVictoryFind(node)) { offerFind(run, node.id, events); return { ok: true, run, events }; }
  completeNode(run, node, events); return { ok: true, run, events };
}

/** Pick one of the three find options: +1 item, and the item opens for later battles. */
export function chooseFindItem(current: ForestRunState, item: ItemKind): ForestRunStep {
  const pending = current.pending;
  if (pending?.kind !== 'find') return fail('Сейчас нечего выбирать.');
  if (!pending.options.includes(item)) return fail('Этого предмета нет среди находок.');
  const run = structuredClone(current), events: ForestRunEvent[] = [{ type: 'item-chosen', nodeId: pending.nodeId, item }];
  run.resources.inventory[item]++;
  run.finds.push({ nodeId: pending.nodeId, item });
  unlock(run.tools, [item], [], events);
  completeNode(run, runNode(run, pending.nodeId)!, events); return { ok: true, run, events };
}

// ---------- Rest: heal or craft (decision of 04.10.2026, like a campfire of Slay the Spire) ----------

/**
 * HP the «heal» choice of a rest restores before the clamp to the maximum: the node's heal today. Run modifiers of the
 * rest heal (talismans «Фляга росы» +1, «Клятва голода» → 0; docs/talismans.md) belong here, so the rest screen, the
 * heal and the save check read one number.
 */
export function restHealValue(_run: ForestRunState, node: ForestMapNode): number {
  return node.content.kind === 'rest' ? node.content.heal : 0;
}
export interface RestRecipeView {
  resource: ResourceKind; item: ItemKind; have: number; cost: number;
  /** Enough of the resource for one more craft now. */
  available: boolean;
  /** The item is not open in this run yet: crafting it opens it for the next battles. */
  opens: boolean;
}
export interface RestView {
  nodeId: string;
  /** «Лечение»: HP it would restore now (after the clamp), its value before the clamp, effects it would clear; gone once crafting began. */
  heal: { amount: number; value: number; clearsEffects: boolean; available: boolean };
  recipes: RestRecipeView[];
  /** Items crafted at this rest so far. */
  crafted: ItemKind[];
  /** The rest can be left now (crafting was chosen); healing completes it by itself. */
  canFinish: boolean;
}
/** The open rest with both choices; null without one. */
export function restView(run: ForestRunState): RestView | null {
  const pending = run.pending, node = pending?.kind === 'rest' ? runNode(run, pending.nodeId) : undefined;
  if (pending?.kind !== 'rest' || !node) return null;
  const { player, materials } = run.resources, crafting = pending.crafted.length > 0, value = restHealValue(run, node);
  return { nodeId: node.id,
    heal: { amount: Math.max(0, Math.min(value, player.maxHp - player.hp)), value, clearsEffects: !!player.damageEffects, available: !crafting },
    recipes: RESOURCE_KINDS.map(resource => {
      const have = materials?.[resource] ?? 0, item = RESOURCES[resource].crafts;
      return { resource, item, have, cost: CRAFT_COST, available: have >= CRAFT_COST, opens: !run.tools.items.includes(item) };
    }),
    crafted: [...pending.crafted], canFinish: crafting };
}

/** Choose «heal» at the open rest: HP up to the maximum, burning, poison and bleeding removed; the rest completes. */
export function restHeal(current: ForestRunState): ForestRunStep {
  const view = restView(current);
  if (!view) return fail('Сейчас нет привала.');
  if (!view.heal.available) return fail('На этом привале выбран крафт: лечения не будет.');
  const run = structuredClone(current), nodeId = view.nodeId, player = run.resources.player, events: ForestRunEvent[] = [];
  player.hp += view.heal.amount; events.push({ type: 'healed', nodeId, amount: view.heal.amount });
  if (player.damageEffects) { delete player.damageEffects; events.push({ type: 'effects-cleared', nodeId }); }
  run.rests.push({ nodeId, choice: 'heal', crafted: [] });
  events.push({ type: 'rest-completed', nodeId, choice: 'heal', healed: view.heal.amount, crafted: [] });
  completeNode(run, runNode(run, nodeId)!, events); return { ok: true, run, events };
}

/**
 * Craft one recipe at the open rest: CRAFT_COST of `resource` become one item. Any number of recipes while resources
 * last; the first one chooses crafting and cancels the heal of this rest. A closed item opens for the run (the battles'
 * `allowedItems`, like a find).
 */
export function restCraft(current: ForestRunState, resource: ResourceKind): ForestRunStep {
  const view = restView(current);
  if (!view) return fail('Сейчас нет привала.');
  const recipe = view.recipes.find(entry => entry.resource === resource);
  if (!recipe) return fail('Такого рецепта нет.');
  if (!recipe.available) return fail(`Нужно ${CRAFT_COST} «${RESOURCES[resource].label}», есть ${recipe.have}.`);
  const run = structuredClone(current), pending = run.pending as Extract<ForestRunPending, { kind: 'rest' }>;
  run.resources.materials![resource] -= CRAFT_COST;
  run.resources.inventory[recipe.item]++;
  pending.crafted.push(recipe.item);
  const events: ForestRunEvent[] = [{ type: 'rest-crafted', nodeId: pending.nodeId, resource, item: recipe.item }];
  unlock(run.tools, [recipe.item], [], events);
  return { ok: true, run, events };
}

/** Leave the open rest after crafting («К карте»): the rest completes with its crafted items. */
export function restFinish(current: ForestRunState): ForestRunStep {
  const view = restView(current);
  if (!view) return fail('Сейчас нет привала.');
  if (!view.canFinish) return fail('Сначала выбери: лечение или крафт.');
  const run = structuredClone(current), nodeId = view.nodeId;
  run.rests.push({ nodeId, choice: 'craft', crafted: [...view.crafted] });
  const events: ForestRunEvent[] = [{ type: 'rest-completed', nodeId, choice: 'craft', healed: 0, crafted: [...view.crafted] }];
  completeNode(run, runNode(run, nodeId)!, events); return { ok: true, run, events };
}

// ---------- Map events (data: forestEvents.ts) ----------

/**
 * Index of the outcome an option gives: rolled from the run seed and the node id (and the option, so options of one
 * event roll apart). The same run always gets the same outcome, also after a reload; nothing else draws from it.
 */
export function eventOutcomeIndex(runSeed: number, nodeId: string, option: EventOption): number {
  if (option.outcomes.length === 1) return 0;
  const roll = mixSeed(forestNodeSeed(runSeed, nodeId), textHash(option.id)) / 0x100000000 * 100;
  let total = 0;
  for (let n = 0; n < option.outcomes.length; n++) { total += option.outcomes[n].chance; if (roll < total) return n; }
  return option.outcomes.length - 1;
}
/** Kinds of the crafting resources an option gives (decided by the seed, so they are shown before the choice). */
export function eventResourceKinds(runSeed: number, nodeId: string, option: EventOption): ResourceKind[] {
  const count = Math.max(0, ...option.outcomes.map(outcome => outcome.effect.resources ?? 0));
  const base = mixSeed(forestNodeSeed(runSeed, nodeId), textHash(`${option.id}:resources`));
  return Array.from({ length: count }, (_, n) => RESOURCE_KINDS[mixSeed(base, n) % RESOURCE_KINDS.length]);
}
const ITEM_NAME: Record<ItemKind, string> = { frost: 'Холод', bomb: 'Бомба', healing: 'Лечение', fire: 'Огонь' };
const energyText = (value: number) => value.toLocaleString('ru-RU', { maximumFractionDigits: 1 });
/** Why the option cannot be taken now ('' — it can): a closed item, energy it cannot pay, HP it cannot spare. */
function optionBlock(run: ForestRunState, option: EventOption): string {
  const closed = ITEM_KINDS.find(item => option.outcomes.some(outcome => (outcome.effect.items?.[item] ?? 0) > 0) && !run.tools.items.includes(item));
  if (closed) return `«${ITEM_NAME[closed]}» ещё не открыт`;
  const { energy, hp } = run.resources.player, energyCost = optionEnergyCost(option), hpCost = optionHpCost(option);
  if (energy < energyCost) return `Нужна энергия: ${energyText(energyCost)} (сейчас ${energyText(energy)})`;
  if (hpCost && hp - hpCost < 1) return `Нужно больше ${hpCost} HP`;
  return '';
}
export interface EventOptionView { id: string; label: string; available: boolean; reason: string; outcomes: { chance: number; text: string }[] }
/** The open event with every option, its outcomes (texts and chances) and whether it can be taken; null without one. */
export function eventView(run: ForestRunState): { nodeId: string; event: ForestEvent; options: EventOptionView[] } | null {
  const pending = run.pending, node = pending?.kind === 'event' ? runNode(run, pending.nodeId) : undefined;
  const event = node?.content.kind === 'event' ? forestEvent(node.content.eventId) : undefined;
  if (!node || !event) return null;
  return { nodeId: node.id, event, options: event.options.map(option => {
    const reason = optionBlock(run, option), kinds = eventResourceKinds(run.seed, node.id, option);
    return { id: option.id, label: option.label, available: !reason, reason,
      outcomes: option.outcomes.map(outcome => ({ chance: outcome.chance, text: describeOutcome(outcome, outcome.effect.resources ? kinds : []) })) };
  }) };
}

/** Take an event option: roll its outcome, apply it (HP never below 1 or above the maximum, energy 0–7), complete the node. */
export function chooseEventOption(current: ForestRunState, optionId: string): ForestRunStep {
  const view = eventView(current);
  if (!view) return fail('Сейчас нет события.');
  const option = eventOption(view.event, optionId), state = view.options.find(entry => entry.id === optionId);
  if (!option || !state) return fail('Такого варианта нет.');
  if (!state.available) return fail(state.reason);
  const run = structuredClone(current), nodeId = view.nodeId, outcome = eventOutcomeIndex(run.seed, nodeId, option);
  const { effect } = option.outcomes[outcome], player = run.resources.player, before = { hp: player.hp, energy: player.energy };
  player.hp = Math.min(player.maxHp, Math.max(1, player.hp + (effect.hp ?? 0)));
  player.energy = Math.min(MAX_ENERGY, Math.max(0, player.energy + (effect.energy ?? 0)));
  const items: Partial<Record<ItemKind, number>> = {};
  for (const item of ITEM_KINDS) if (effect.items?.[item]) { run.resources.inventory[item] += effect.items[item]!; items[item] = effect.items[item]; }
  const materials = effect.resources ? eventResourceKinds(run.seed, nodeId, option).slice(0, effect.resources) : [];
  for (const kind of materials) (run.resources.materials ??= emptyMaterials())[kind]++;
  run.eventChoices.push({ nodeId, option: option.id, outcome });
  const events: ForestRunEvent[] = [{ type: 'event-resolved', nodeId, option: option.id, outcome, text: state.outcomes[outcome].text,
    changes: { hp: player.hp - before.hp, energy: player.energy - before.energy, items, materials } }];
  completeNode(run, runNode(run, nodeId)!, events); return { ok: true, run, events };
}

/** `lost`: the node whose battle ended the run in a defeat; `skipped`: a trunk node of a run that started past the trunk. */
export type ForestNodeStatus = 'visited' | 'current' | 'in-progress' | 'available' | 'locked' | 'lost' | 'skipped';
export interface ForestRunView {
  nodes: { node: ForestMapNode; status: ForestNodeStatus }[];
  available: string[];
  battlesWon: number;
  resources: ForestRunResources;
  tools: ForestRunTools;
  pending: ForestRunPending | null;
  result: ForestRunResult | null;
}

/** Everything the map screen needs in one read-only snapshot. */
export function forestRunView(run: ForestRunState): ForestRunView {
  const available = availableNodes(run).map(node => node.id);
  const status = (node: ForestMapNode): ForestNodeStatus => run.pending?.nodeId === node.id ? 'in-progress'
    : run.result?.outcome === 'defeat' && run.result.nodeId === node.id ? 'lost'
    : node.id === run.currentNodeId ? 'current' : run.visited.includes(node.id) ? 'visited' : available.includes(node.id) ? 'available'
    : run.skippedTrunk && isTrunkNode(node) ? 'skipped' : 'locked';
  // Available pool nodes show the battle or event they would get; entered ones their pick.
  return { nodes: forestRunMap(run).nodes.map(base => { const node = available.includes(base.id) ? previewNode(run, base.id)! : runNode(run, base.id)!; return { node, status: status(node) }; }), available,
    battlesWon: run.visited.filter(id => { const node = runNode(run, id); return !!node && isBattleNode(node); }).length,
    resources: structuredClone(run.resources), tools: structuredClone(run.tools), pending: structuredClone(run.pending), result: run.result && { ...run.result } };
}

export function serializeForestRun(run: ForestRunState): string { return JSON.stringify(run); }

const isRecord = (value: unknown): value is Record<string, unknown> => !!value && typeof value === 'object' && !Array.isArray(value);
const isCount = (value: unknown) => typeof value === 'number' && Number.isInteger(value) && value >= 0;
const isSeed = (value: unknown) => typeof value === 'number' && Number.isInteger(value) && value >= 0 && value <= 0xffffffff;
const EFFECT_KEYS = ['burning', 'burningTurns', 'poison', 'bleeding', 'bleedingSteps', 'creditedBurning', 'creditedPoison', 'creditedBleeding'];

function validResources(value: unknown): value is ForestRunResources {
  if (!isRecord(value) || !isRecord(value.player) || !isRecord(value.inventory)) return false;
  const { hp, maxHp, energy, damageEffects } = value.player;
  // A living cat: a battle is never won at 0 HP, and a defeat keeps the entry resources.
  if (maxHp !== FOREST_RUN_START_HP || !isCount(hp) || (hp as number) < 1 || (hp as number) > maxHp) return false;
  if (typeof energy !== 'number' || !Number.isFinite(energy) || energy < 0 || energy > MAX_ENERGY) return false;
  if (damageEffects !== undefined && (!isRecord(damageEffects) || Object.entries(damageEffects).some(([key, amount]) => !EFFECT_KEYS.includes(key) || !isCount(amount)))) return false;
  const inventory = value.inventory, materials = value.materials;
  if (materials !== undefined && (!isRecord(materials) || Object.keys(materials).length !== RESOURCE_KINDS.length || !RESOURCE_KINDS.every(resource => isCount(materials[resource])))) return false;
  return Object.keys(inventory).length === ITEM_KINDS.length && ITEM_KINDS.every(item => isCount(inventory[item]));
}
function validTools(value: unknown): value is ForestRunTools {
  return isRecord(value) && Array.isArray(value.items) && Array.isArray(value.abilities)
    && value.items.every(item => ITEM_KINDS.includes(item as ItemKind)) && value.abilities.every(ability => ABILITY_KINDS.includes(ability as AbilityKind));
}

/**
 * Tools the run must have opened after `visited` (plus the entered node's grants), replayed from the graph, the finds
 * and the items crafted at rests (`crafts` by rest node id; the open rest included).
 */
function expectedTools(visited: ForestMapNode[], finds: ForestRunState['finds'], entered: ForestMapNode | null, won: boolean,
  crafts: ReadonlyMap<string, ItemKind[]>): ForestRunTools {
  const tools: ForestRunTools = { items: [], abilities: [] }, sink: ForestRunEvent[] = [];
  let taken = 0;
  for (const node of visited) {
    unlock(tools, node.grants?.items, node.grants?.abilities, sink);
    if (isBattleNode(node)) unlock(tools, node.rewardGrants?.items, node.rewardGrants?.abilities, sink);
    if (node.type === 'find' || hasVictoryFind(node)) unlock(tools, [finds[taken++].item], [], sink);
    unlock(tools, crafts.get(node.id), [], sink);
  }
  if (entered) unlock(tools, entered.grants?.items, entered.grants?.abilities, sink);
  if (entered && won) unlock(tools, entered.rewardGrants?.items, entered.rewardGrants?.abilities, sink);
  if (entered) unlock(tools, crafts.get(entered.id), [], sink);
  return tools;
}
/** A rest record of a save: `heal` with nothing crafted, or `craft` with one or more items. */
function validRest(value: unknown, nodeId: string): value is ForestRunRest {
  if (!isRecord(value) || Object.keys(value).length !== 3 || value.nodeId !== nodeId || !Array.isArray(value.crafted)) return false;
  if (!value.crafted.every(item => ITEM_KINDS.includes(item as ItemKind))) return false;
  return value.choice === 'heal' ? value.crafted.length === 0 : value.choice === 'craft' && value.crafted.length > 0;
}
const sameTools = (a: ForestRunTools, b: ForestRunTools) => a.items.length === b.items.length && a.abilities.length === b.abilities.length
  && a.items.every(item => b.items.includes(item)) && a.abilities.every(ability => b.abilities.includes(ability));

/** Upper bound of each item: node grants and taken finds. */
/** Authored elites of a node's battle (0 for anything else): the most items its loot can add. */
function battleElites(node: ForestMapNode): number {
  return nodeBattleTemplate(node)?.definition.enemies.filter(enemy => enemy.elite).length ?? 0;
}
/** A battle node where random elites may appear (map rows from RUN_PRESSURE_FIRST_ROW, elite.ts). */
const randomElitesPossible = (node: ForestMapNode): boolean => !!nodeBattleTemplate(node) && node.row >= RUN_PRESSURE_FIRST_ROW;
/** Resources a node's exit chest adds (exitRules.ts): CHEST_RESOURCES in a battle with an exit door, else 0. */
const chestResources = (node: ForestMapNode): number => nodeBattleTemplate(node)?.definition.completion === 'exit' ? CHEST_RESOURCES : 0;

function inventoryCap(visited: ForestMapNode[], finds: ForestRunState['finds'], entered: ForestMapNode | null, loot: ForestRunState['loot'],
  events: { items: Partial<Record<ItemKind, number>>; materials: ResourceKind[] }[], crafted: ItemKind[]): Record<LootKind, number> {
  const cap: Record<LootKind, number> = { frost: 0, bomb: 0, healing: 0, fire: 0, ...emptyMaterials() };
  for (const node of [...visited, ...entered ? [entered] : []]) {
    for (const item of ITEM_KINDS) cap[item] += node.grants?.inventory?.[item] ?? 0;
  }
  for (const find of finds) cap[find.item]++;
  for (const gain of events) {
    for (const item of ITEM_KINDS) cap[item] += gain.items[item] ?? 0;
    for (const kind of gain.materials) cap[kind]++;
  }
  for (const gain of loot) cap[gain.item] += gain.count;
  for (const item of crafted) cap[item]++;
  return cap;
}

/** The map of a save: version 1 walks the authored graph; version 2 names it or stores a generated map. Null if invalid. */
function savedMap(value: Record<string, unknown>): ForestRunMapRef | null {
  if (value.version === 1) return value.map === undefined && value.picks === undefined ? { kind: 'authored' } : null;
  const map = value.map;
  if (!isRecord(map)) return null;
  if (map.kind === 'authored') return Object.keys(map).length === 1 ? { kind: 'authored' } : null;
  if (map.kind !== 'generated' || validateStoredMap(map).length) return null;
  return { kind: 'generated', generator: map.generator as number, nodes: structuredClone(map.nodes) as GeneratedForestMap['nodes'] };
}

/**
 * Parse a saved run. Returns null for anything that is not a consistent run of its map: the authored graph (version 1
 * and authored version 2 saves) or the generated map the save carries.
 */
export function parseForestRun(text: string): ForestRunState | null {
  let value: unknown;
  try { value = JSON.parse(text); } catch { return null; }
  if (!isRecord(value) || (value.version !== 1 && value.version !== FOREST_RUN_VERSION) || !isSeed(value.seed)) return null;
  if (!Array.isArray(value.visited) || !validResources(value.resources) || !validTools(value.tools)) return null;
  if (value.skippedTrunk !== undefined && value.skippedTrunk !== true) return null;
  const mapRef = savedMap(value);
  if (!mapRef) return null;
  const map = forestRunMap({ map: mapRef }), starts = map.starts(value.skippedTrunk === true);
  // Replaying the visited ids through the graph rejects saves from another map layout.
  let at: string | null = null;
  for (const id of value.visited) {
    const allowed: string[] = at === null ? starts : map.node(at)?.next ?? [];
    if (typeof id !== 'string' || !allowed.includes(id)) return null;
    at = id;
  }
  if (value.currentNodeId !== at) return null;
  const visited = value.visited as string[], seed = value.seed as number;
  const nextIds = at === null ? starts : map.node(at)!.next;
  const pending = value.pending, result = value.result;
  // The entered, not completed node: the open one, or the node whose battle was lost (its grants were applied on entering).
  const enteredId = isRecord(pending) && typeof pending.nodeId === 'string' ? pending.nodeId
    : isRecord(result) && result.outcome === 'defeat' && typeof result.nodeId === 'string' ? result.nodeId : null;
  if (enteredId !== null && !nextIds.includes(enteredId)) return null;
  // Pool picks: one per entered pool node of a generated map, in entering order, a battle of that node's pool (with the
  // tools open there) or a known event that the run had not met yet. Pools may grow later: the save keeps its picks.
  const picks = value.version === 1 && value.picks === undefined ? [] : value.picks;
  const entering = [...visited, ...enteredId !== null ? [enteredId] : []];
  const poolIds = entering.filter(id => map.node(id)!.content.kind === 'pool');
  if (!Array.isArray(picks) || picks.length !== poolIds.length) return null;
  // Finds: one choice per visited find or hard-battle node, in order, from that node's offered items (the type and id
  // of a node do not depend on its pick).
  const findNodes = visited.map(id => map.node(id)!).filter(node => node.type === 'find' || hasVictoryFind(node));
  const finds = value.finds;
  if (!Array.isArray(finds) || finds.length !== findNodes.length || finds.some((find, n) => !isRecord(find) || find.nodeId !== findNodes[n].id
    || !findOptions(seed, findNodes[n]).includes(find.item as ItemKind))) return null;
  const typedFinds = finds as ForestRunState['finds'];
  // Rests: one record per visited rest node, in order (a rest is never a pool node). Saves before 04.10.2026 have none:
  // their rests healed on entering. The open rest keeps its crafts in `pending`.
  const restIds = visited.filter(id => map.node(id)!.content.kind === 'rest');
  const rests = value.rests === undefined ? restIds.map(nodeId => ({ nodeId, choice: 'heal', crafted: [] })) : value.rests;
  if (!Array.isArray(rests) || rests.length !== restIds.length || rests.some((rest, n) => !validRest(rest, restIds[n]))) return null;
  const typedRests = rests as ForestRunRest[];
  const openRest = isRecord(pending) && pending.kind === 'rest' ? pending : null;
  if (openRest && (Object.keys(openRest).length !== 3 || !Array.isArray(openRest.crafted) || !openRest.crafted.every(item => ITEM_KINDS.includes(item as ItemKind)))) return null;
  const crafts = new Map<string, ItemKind[]>(typedRests.filter(rest => rest.choice === 'craft').map(rest => [rest.nodeId, rest.crafted]));
  if (openRest && typeof openRest.nodeId === 'string' && (openRest.crafted as ItemKind[]).length) crafts.set(openRest.nodeId, openRest.crafted as ItemKind[]);
  const typedPicks: ForestRunPick[] = [];
  for (let n = 0; n < picks.length; n++) {
    const pick = picks[n], base = map.node(poolIds[n])!;
    if (!isRecord(pick) || pick.nodeId !== base.id) return null;
    const before = entering.slice(0, entering.indexOf(base.id)).map(id => runNode({ map: mapRef, picks: typedPicks }, id)!);
    if (base.type === 'event') {
      if (Object.keys(pick).length !== 2 || typeof pick.eventId !== 'string' || !forestEvent(pick.eventId)) return null;
      const met = typedPicks.flatMap(entry => entry.eventId ? [entry.eventId] : []);
      if (met.includes(pick.eventId) && met.length < Object.keys(FOREST_EVENTS).length) return null;
    } else {
      if (Object.keys(pick).length !== 2 || typeof pick.battleId !== 'string') return null;
      const tools = expectedTools(before, typedFinds, base, false, crafts);
      if (!poolCandidates({ row: base.row, type: base.type as PoolBattleType, lane: base.lane }, tools).includes(pick.battleId)) return null;
    }
    typedPicks.push(base.type === 'event' ? { nodeId: base.id, eventId: pick.eventId as string } : { nodeId: base.id, battleId: pick.battleId as string });
  }
  const nodeAt = (id: string) => runNode({ map: mapRef, picks: typedPicks }, id);
  // A completed node without transitions must carry the run result; otherwise the run would be stuck.
  if (pending === null && result === null && !nextIds.length) return null;
  const entered = enteredId !== null ? nodeAt(enteredId) ?? null : null;
  const wonHard = pending !== null && isRecord(pending) && pending.kind === 'find' && !!entered && hasVictoryFind(entered);
  const visitedNodes = visited.map(id => nodeAt(id)!);
  if (!sameTools(value.tools as ForestRunTools, expectedTools(visitedNodes, typedFinds, entered, wonHard, crafts))) return null;
  // Elite loot of won battles: completed battle nodes, or the hard battle whose find is still pending; one entry per
  // node and kind. Consumables come only from authored elites (at most one each). Resources also come from random
  // elites, which appear in battles from row 5 in any number over a battle: there they are not bounded by count. A
  // battle with an exit door adds its chest's resources (exitRules.ts).
  const loot = value.loot === undefined ? [] : value.loot;
  if (!Array.isArray(loot) || loot.some(gain => !isRecord(gain) || typeof gain.nodeId !== 'string'
    || !(visited.includes(gain.nodeId) || wonHard && entered?.id === gain.nodeId)
    || !(ITEM_KINDS.includes(gain.item as ItemKind) || isResource(gain.item as string)) || !isCount(gain.count) || (gain.count as number) < 1)) return null;
  const typedLoot = loot as ForestRunState['loot'];
  const perNode = new Map<string, number>(), perNodeItems = new Map<string, number>(), pairs = new Set<string>();
  for (const gain of typedLoot) {
    if (pairs.has(`${gain.nodeId}:${gain.item}`)) return null;
    pairs.add(`${gain.nodeId}:${gain.item}`);
    // Resources of a node with random elites are unbounded; everything else counts against the authored elites.
    if (!(isResource(gain.item) && randomElitesPossible(nodeAt(gain.nodeId)!))) perNode.set(gain.nodeId, (perNode.get(gain.nodeId) ?? 0) + gain.count);
    if (!isResource(gain.item)) perNodeItems.set(gain.nodeId, (perNodeItems.get(gain.nodeId) ?? 0) + gain.count);
  }
  for (const [nodeId, count] of perNode) if (count > battleElites(nodeAt(nodeId)!) + chestResources(nodeAt(nodeId)!)) return null;
  for (const [nodeId, count] of perNodeItems) if (count > battleElites(nodeAt(nodeId)!)) return null;
  // Event choices: one per visited event node, in order, an option of its event with the outcome the seed rolls.
  const eventNodes = visitedNodes.filter(node => node.content.kind === 'event');
  const choices = value.eventChoices === undefined ? [] : value.eventChoices;
  if (!Array.isArray(choices) || choices.length !== eventNodes.length) return null;
  const eventGains: { items: Partial<Record<ItemKind, number>>; materials: ResourceKind[] }[] = [];
  for (let n = 0; n < choices.length; n++) {
    const choice = choices[n], node = eventNodes[n], content = node.content as { kind: 'event'; eventId: string };
    const option = isRecord(choice) && typeof choice.option === 'string' ? eventOption(forestEvent(content.eventId)!, choice.option) : undefined;
    if (!option || !isRecord(choice) || choice.nodeId !== node.id || choice.outcome !== eventOutcomeIndex(seed, node.id, option)) return null;
    const { effect } = option.outcomes[choice.outcome as number];
    eventGains.push({ items: effect.items ?? {}, materials: eventResourceKinds(seed, node.id, option).slice(0, effect.resources ?? 0) });
  }
  const crafted = [...crafts.values()].flat();
  const cap = inventoryCap(visitedNodes, typedFinds, entered, typedLoot, eventGains, crafted), inventory = (value.resources as ForestRunResources).inventory;
  if (ITEM_KINDS.some(item => inventory[item] > cap[item])) return null;
  // Resources come from elite loot and exit chests (both recorded in `loot`) and events, and are spent at rests: a rest
  // crafts only from what the run had gained before it, and what is left is at most the gains less the spending.
  const stock = emptyMaterials(), spent = emptyMaterials();
  for (const id of entering) {
    for (const gain of typedLoot) if (gain.nodeId === id && isResource(gain.item)) stock[gain.item] += gain.count;
    for (const kind of eventGains[eventNodes.findIndex(node => node.id === id)]?.materials ?? []) stock[kind]++;
    for (const item of crafts.get(id) ?? []) {
      const resource = craftSource(item);
      stock[resource] -= CRAFT_COST; spent[resource] += CRAFT_COST;
      if (stock[resource] < 0) return null;
    }
  }
  const materials = (value.resources as ForestRunResources).materials;
  if (materials && RESOURCE_KINDS.some(resource => materials[resource] > cap[resource] - spent[resource])) return null;
  if (pending !== null) {
    if (!isRecord(pending) || typeof pending.nodeId !== 'string' || !nextIds.includes(pending.nodeId)) return null;
    const node = nodeAt(pending.nodeId)!;
    if (pending.kind === 'battle') {
      if (!isBattleNode(node) || node.content.kind === 'in-development' || !isSeed(pending.seed) || pending.seed !== forestNodeSeed(value.seed as number, node.id)
        || !validResources(pending.entry) || !validTools(pending.tools) || pending.defeats !== undefined && !isCount(pending.defeats)) return null;
      // While a battle is open the run still holds the entry snapshot: a defeat never changes resources.
      if (JSON.stringify(pending.entry) !== JSON.stringify(value.resources) || !sameTools(pending.tools, value.tools as ForestRunTools)) return null;
    } else if (pending.kind === 'event') {
      if (node.content.kind !== 'event' || Object.keys(pending).length !== 2) return null;
    } else if (pending.kind === 'rest') {
      if (node.content.kind !== 'rest' || !openRest) return null;
    } else if (pending.kind === 'find') {
      if (node.type !== 'find' && !hasVictoryFind(node) || JSON.stringify(pending.options) !== JSON.stringify(findOptions(seed, node))) return null;
    } else return null;
  }
  if (result !== null) {
    if (!isRecord(result) || pending !== null) return null;
    if (result.outcome === 'victory') { if (result.nodeId !== at || nodeAt(at!)?.type !== 'boss') return null; }
    else if (result.outcome === 'boss-in-development') {
      if (typeof result.nodeId !== 'string' || !nextIds.includes(result.nodeId) || nodeAt(result.nodeId)?.content.kind !== 'in-development') return null;
    } else if (result.outcome === 'defeat') {
      // The lost battle was entered from the current node and never completed.
      const lost = typeof result.nodeId === 'string' ? nodeAt(result.nodeId) : undefined;
      if (!lost || !nextIds.includes(lost.id) || !nodeRunTemplate(lost)) return null;
    } else return null;
  }
  if (value.score !== undefined && !isCount(value.score)) return null;
  // Version 1 saves get the version 2 fields in the order a new run has them.
  const { version: _version, seed: _seed, map: _map, picks: _picks, ...rest } = structuredClone(value);
  const run = { version: FOREST_RUN_VERSION, seed, map: mapRef, picks: typedPicks, ...rest, loot: structuredClone(typedLoot),
    eventChoices: structuredClone(choices), rests: structuredClone(typedRests), score: (value.score as number | undefined) ?? 0 } as unknown as ForestRunState;
  // Saves before 04.10.2026 count defeats of the open battle; a defeat now ends the run, so the counter has no meaning.
  if (run.pending?.kind === 'battle') delete (run.pending as { defeats?: number }).defeats;
  return run;
}
