#!/usr/bin/env bash
# Finds references in README/docs/AGENTS to files, npm scripts and code symbols that no longer exist.
cd "$(dirname "$0")/../../../.." || exit 2
DOCS=(README.md AGENTS.md TRANSFER-RU.md docs)
status=0
echo "== Missing file paths =="
grep -rhoE '(src|docs|tests|public|artifacts)/[A-Za-z0-9_./-]+\.(ts|md|json|png|mjs|py|css|html)' "${DOCS[@]}" | sort -u | while read -r p; do
  # docs/ links may be relative to docs/
  [ -e "$p" ] || [ -e "docs/$p" ] || { case "$p" in artifacts/*.png|artifacts/*.jpg) echo "  (screenshot, regenerated by npm test) $p";; *) echo "  MISSING $p";; esac; }
done
echo "== Unknown npm scripts =="
scripts=$(node -e 'console.log(Object.keys(require("./package.json").scripts).join("\n"))')
grep -rhoE 'npm run [a-z:-]+' "${DOCS[@]}" | awk '{print $3}' | grep -v ':$' | sort -u | while read -r s; do
  echo "$scripts" | grep -qx "$s" || echo "  UNKNOWN npm run $s"
done
echo "== Backticked identifiers not found in src/ (review manually) =="
grep -rhoE '`[a-z][A-Za-z0-9]{5,}`' "${DOCS[@]}" | tr -d '`' | sort -u | while read -r id; do
  grep -rqw "$id" src tests package.json 2>/dev/null || echo "  $id"
done
exit $status
